# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

lista_regiones = [
	[1, "I REGIÓN DE TARAPACÁ"],
	[2, "II REGIÓN DE ANTOFAGASTA"],
	[3, "III REGIÓN DE ATACAMA"],
	[4, "IV REGIÓN DE COQUIMBO"],
	[5, "V REGIÓN DE VALPARAÍSO"],
	[6, "VI REGIÓN DEL LIBERTADOR GRAL. BERNARDO O\'HIGGINS"],
	[7, "VII REGIÓN DEL MAULE"],
	[8, "VIII REGIÓN DEL BIOBÍO"],
	[9, "IX REGIÓN DE LA ARAUCANÍA"],
	[10, "X REGIÓN DE LOS LAGOS"],
	[11, "XI REGIÓN DE AISÉN DEL GRAL. CARLOS IBAÑEZ DEL CAMPO"],
	[12, "XII REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA"],
	[13, "XIII REGIÓN METROPOLITANA DE SANTIAGO"],
	[14, "XIV REGIÓN DE LOS RÍOS"],
	[15, "XV REGIÓN DE ARICA Y PARINACOTA"]
]

lista_regiones.each do |id, nombre|
	Region.create(region_id: id, region_nombre: nombre)
end

[
{:provincia_id => 1, :region_id => 1, :provincia_nombre => "Iquique"},
{:provincia_id => 2, :region_id => 1, :provincia_nombre => "Tamarugal"},
{:provincia_id => 3, :region_id => 2, :provincia_nombre => "Antofagasta"},
{:provincia_id => 4, :region_id => 2, :provincia_nombre => "El Loa"},
{:provincia_id => 5, :region_id => 2, :provincia_nombre => "Tocopilla"},
{:provincia_id => 6, :region_id => 3, :provincia_nombre => "Copiapó"},
{:provincia_id => 7, :region_id => 3, :provincia_nombre => "Chañaral"},
{:provincia_id => 8, :region_id => 3, :provincia_nombre => "Huasco"},
{:provincia_id => 9, :region_id => 4, :provincia_nombre => "Elqui"},
{:provincia_id => 10, :region_id => 4, :provincia_nombre => "Choapa"},
{:provincia_id => 11, :region_id => 4, :provincia_nombre => "Limarí"},
{:provincia_id => 12, :region_id => 5, :provincia_nombre => "Valparaíso"},
{:provincia_id => 13, :region_id => 5, :provincia_nombre => "Isla de Pascua"},
{:provincia_id => 14, :region_id => 5, :provincia_nombre => "Los Andes"},
{:provincia_id => 15, :region_id => 5, :provincia_nombre => "Petorca"},
{:provincia_id => 16, :region_id => 5, :provincia_nombre => "Quillota"},
{:provincia_id => 17, :region_id => 5, :provincia_nombre => "San Antonio"},
{:provincia_id => 18, :region_id => 5, :provincia_nombre => "San Felipe de Aconcagua"},
{:provincia_id => 19, :region_id => 5, :provincia_nombre => "Marga Marga"},
{:provincia_id => 20, :region_id => 5, :provincia_nombre => "Cachapoal"},
{:provincia_id => 21, :region_id => 5, :provincia_nombre => "Cardenal Caro"},
{:provincia_id => 22, :region_id => 5, :provincia_nombre => "Colchagua"},
{:provincia_id => 23, :region_id => 7, :provincia_nombre => "Talca"},
{:provincia_id => 24, :region_id => 7, :provincia_nombre => "Cauquenes"},
{:provincia_id => 25, :region_id => 7, :provincia_nombre => "Curicó"},
{:provincia_id => 26, :region_id => 7, :provincia_nombre => "Linares"},
{:provincia_id => 27, :region_id => 8, :provincia_nombre => "Concepción"},
{:provincia_id => 28, :region_id => 8, :provincia_nombre => "Arauco"},
{:provincia_id => 29, :region_id => 8, :provincia_nombre => "Biobío"},
{:provincia_id => 30, :region_id => 8, :provincia_nombre => "Ñuble"},
{:provincia_id => 31, :region_id => 9, :provincia_nombre => "Cautín"},
{:provincia_id => 32, :region_id => 9, :provincia_nombre => "Malleco"},
{:provincia_id => 33, :region_id => 10, :provincia_nombre => "Valdivia"},
{:provincia_id => 34, :region_id => 10, :provincia_nombre => "Ranco"},
{:provincia_id => 35, :region_id => 11, :provincia_nombre => "Llanquihue"},
{:provincia_id => 36, :region_id => 11, :provincia_nombre => "Chiloé"},
{:provincia_id => 37, :region_id => 11, :provincia_nombre => "Osorno"},
{:provincia_id => 38, :region_id => 11, :provincia_nombre => "Palena"},
{:provincia_id => 39, :region_id => 12, :provincia_nombre => "Coihaique"},
{:provincia_id => 40, :region_id => 12, :provincia_nombre => "Aisén"},
{:provincia_id => 41, :region_id => 12, :provincia_nombre => "Capitán Prat"},
{:provincia_id => 42, :region_id => 12, :provincia_nombre => "General Carrera"},
{:provincia_id => 43, :region_id => 13, :provincia_nombre => "Magallanes"},
{:provincia_id => 44, :region_id => 13, :provincia_nombre => "Antártica Chilena"},
{:provincia_id => 45, :region_id => 13, :provincia_nombre => "Tierra del Fuego"},
{:provincia_id => 46, :region_id => 13, :provincia_nombre => "Ultima Esperanza"},
{:provincia_id => 47, :region_id => 14, :provincia_nombre => "Santiago"},
{:provincia_id => 48, :region_id => 14, :provincia_nombre => "Cordillera"},
{:provincia_id => 49, :region_id => 14, :provincia_nombre => "Chacabuco"},
{:provincia_id => 50, :region_id => 14, :provincia_nombre => "Maipo"},
{:provincia_id => 51, :region_id => 14, :provincia_nombre => "Melipilla"},
{:provincia_id => 52, :region_id => 14, :provincia_nombre => "Talagante"},
{:provincia_id => 53, :region_id => 15, :provincia_nombre => "Arica"},
{:provincia_id => 54, :region_id => 15, :provincia_nombre => "Parinacota"},

].each do |provincia_unit|
	ProvinciaUnit.find_or_create_by(provincia_unit)
end

[
	{:comuna_id => 1,  :provincia_id => 1, :comuna_nombre => "Iquique"},
	{:comuna_id => 2,  :provincia_id => 1, :comuna_nombre => "Alto Hospicio"},
	{:comuna_id => 3,  :provincia_id => 2, :comuna_nombre => "Pozo Almonte"},
	{:comuna_id => 4,  :provincia_id => 2, :comuna_nombre => "Camiña"},
	{:comuna_id => 5,  :provincia_id => 2, :comuna_nombre => "Colchane"},
	{:comuna_id => 6,  :provincia_id => 2, :comuna_nombre => "Huara"},
	{:comuna_id => 7,  :provincia_id => 2, :comuna_nombre => "Pica"},
	{:comuna_id => 8,  :provincia_id => 3, :comuna_nombre => "Antofagasta"},
	{:comuna_id => 9,  :provincia_id => 3, :comuna_nombre => "Mejillones"},
	{:comuna_id => 10, :provincia_id => 3, :comuna_nombre => "Sierra Gorda"},
	{:comuna_id => 11, :provincia_id => 3, :comuna_nombre => "Taltal"},
	{:comuna_id => 12, :provincia_id => 4, :comuna_nombre => "Calama"},
	{:comuna_id => 13, :provincia_id => 4, :comuna_nombre => "Ollagüe"},
	{:comuna_id => 14, :provincia_id => 4, :comuna_nombre => "San Pedro de Atacama"},
	{:comuna_id => 15, :provincia_id => 5, :comuna_nombre => "Tocopilla"},
	{:comuna_id => 16, :provincia_id => 5, :comuna_nombre => "María Elena"},
	{:comuna_id => 17, :provincia_id => 6, :comuna_nombre => "Copiapó"},
	{:comuna_id => 18, :provincia_id => 6, :comuna_nombre => "Caldera"},
	{:comuna_id => 19, :provincia_id => 6, :comuna_nombre => "Tierra Amarilla"},
	{:comuna_id => 20, :provincia_id => 7, :comuna_nombre => "Chañaral"},
	{:comuna_id => 21, :provincia_id => 7, :comuna_nombre => "Diego de Almagro"},
	{:comuna_id => 22, :provincia_id => 8, :comuna_nombre => "Vallenar"},
	{:comuna_id => 23, :provincia_id => 8, :comuna_nombre => "Alto del Carmen"},
	{:comuna_id => 24, :provincia_id => 8, :comuna_nombre => "Freirina"},
	{:comuna_id => 25, :provincia_id => 8, :comuna_nombre => "Huasco"},
	{:comuna_id => 26, :provincia_id => 9, :comuna_nombre => "La Serena"},
	{:comuna_id => 27, :provincia_id => 9, :comuna_nombre => "Coquimbo"},
	{:comuna_id => 28, :provincia_id => 9, :comuna_nombre => "Andacollo"},
	{:comuna_id => 29, :provincia_id => 9, :comuna_nombre => "La Higuera"},
	{:comuna_id => 30, :provincia_id => 9, :comuna_nombre => "Paiguano"},
	{:comuna_id => 31, :provincia_id => 9, :comuna_nombre => "Vicuña"},
	{:comuna_id => 32, :provincia_id => 10, :comuna_nombre => "Illapel"},
	{:comuna_id => 33, :provincia_id => 10, :comuna_nombre => "Canela"},
	{:comuna_id => 34, :provincia_id => 10, :comuna_nombre => "Los Vilos"},
	{:comuna_id => 35, :provincia_id => 10, :comuna_nombre => "Salamanca"},
	{:comuna_id => 36, :provincia_id => 11, :comuna_nombre => "Ovalle"},
	{:comuna_id => 37, :provincia_id => 11, :comuna_nombre => "Combarbalá"},
	{:comuna_id => 38, :provincia_id => 11, :comuna_nombre => "Monte Patria"},
	{:comuna_id => 39, :provincia_id => 11, :comuna_nombre => "Punitaqui"},
	{:comuna_id => 40, :provincia_id => 11, :comuna_nombre => "Río Hurtado"},
	{:comuna_id => 41, :provincia_id => 12, :comuna_nombre => "Valparaíso"},
	{:comuna_id => 42, :provincia_id => 12, :comuna_nombre => "Casablanca"},
	{:comuna_id => 43, :provincia_id => 12, :comuna_nombre => "Concón"},
	{:comuna_id => 44, :provincia_id => 12, :comuna_nombre => "Juan Fernández"},
	{:comuna_id => 45, :provincia_id => 12, :comuna_nombre => "Puchuncaví"},
	{:comuna_id => 46, :provincia_id => 12, :comuna_nombre => "Quintero"},
	{:comuna_id => 47, :provincia_id => 12, :comuna_nombre => "Viña del Mar"},
	{:comuna_id => 48, :provincia_id => 13, :comuna_nombre => "Isla de Pascua"},
	{:comuna_id => 49, :provincia_id => 14, :comuna_nombre => "Los Andes"},
	{:comuna_id => 50, :provincia_id => 14, :comuna_nombre => "Calle Larga"},
	{:comuna_id => 51, :provincia_id => 14, :comuna_nombre => "Rinconada"},
	{:comuna_id => 52, :provincia_id => 14, :comuna_nombre => "San Esteban"},
	{:comuna_id => 53, :provincia_id => 15, :comuna_nombre => "La Ligua"},
	{:comuna_id => 54, :provincia_id => 15, :comuna_nombre => "Cabildo"},
	{:comuna_id => 55, :provincia_id => 15, :comuna_nombre => "Papudo"},
	{:comuna_id => 56, :provincia_id => 15, :comuna_nombre => "Petorca"},
	{:comuna_id => 57, :provincia_id => 15, :comuna_nombre => "Zapallar"},
	{:comuna_id => 58, :provincia_id => 16, :comuna_nombre => "La Ligua"},
	{:comuna_id => 59, :provincia_id => 16, :comuna_nombre => "Cabildo"},
	{:comuna_id => 60, :provincia_id => 16, :comuna_nombre => "Papudo"},
	{:comuna_id => 61, :provincia_id => 16, :comuna_nombre => "Petorca"},
	{:comuna_id => 62, :provincia_id => 16, :comuna_nombre => "Zapallar"},
	{:comuna_id => 63, :provincia_id => 17, :comuna_nombre => "San Antonio"},
	{:comuna_id => 64, :provincia_id => 17, :comuna_nombre => "Algarrobo"},
	{:comuna_id => 65, :provincia_id => 17, :comuna_nombre => "Cartagena"},
	{:comuna_id => 66, :provincia_id => 17, :comuna_nombre => "El Quisco"},
	{:comuna_id => 67, :provincia_id => 17, :comuna_nombre => "El Tabo"},
	{:comuna_id => 68, :provincia_id => 17, :comuna_nombre => "Santo Domingo"},
	{:comuna_id => 69, :provincia_id => 18, :comuna_nombre => "San Felipe"},
	{:comuna_id => 70, :provincia_id => 18, :comuna_nombre => "Catemu"},
	{:comuna_id => 71, :provincia_id => 18, :comuna_nombre => "Llaillay"},
	{:comuna_id => 72, :provincia_id => 18, :comuna_nombre => "Panquehue"},
	{:comuna_id => 73, :provincia_id => 18, :comuna_nombre => "Putaendo"},
	{:comuna_id => 74, :provincia_id => 18, :comuna_nombre => "Santa María"},
	{:comuna_id => 75, :provincia_id => 19, :comuna_nombre => "Limache"},
	{:comuna_id => 76, :provincia_id => 19, :comuna_nombre => "Quilpué"},
	{:comuna_id => 77, :provincia_id => 19, :comuna_nombre => "Villa Alemana"},
	{:comuna_id => 78, :provincia_id => 19, :comuna_nombre => "Olmué"},
	{:comuna_id => 79, :provincia_id => 20, :comuna_nombre => "Rancagua"},
	{:comuna_id => 80, :provincia_id => 20, :comuna_nombre => "Codegua"},
	{:comuna_id => 81, :provincia_id => 20, :comuna_nombre => "Coinco"},
	{:comuna_id => 82, :provincia_id => 20, :comuna_nombre => "Coltauco"},
	{:comuna_id => 83, :provincia_id => 20, :comuna_nombre => "Doñihue"},
	{:comuna_id => 84, :provincia_id => 20, :comuna_nombre => "Graneros"},
	{:comuna_id => 85, :provincia_id => 20, :comuna_nombre => "Las Cabras"},
	{:comuna_id => 86, :provincia_id => 20, :comuna_nombre => "Machalí"},
	{:comuna_id => 87, :provincia_id => 20, :comuna_nombre => "Malloa"},
	{:comuna_id => 88, :provincia_id => 20, :comuna_nombre => "Mostazal"},
	{:comuna_id => 89, :provincia_id => 20, :comuna_nombre => "Olivar"},
	{:comuna_id => 90, :provincia_id => 20, :comuna_nombre => "Peumo"},
	{:comuna_id => 91, :provincia_id => 20, :comuna_nombre => "Pichidegua"},
	{:comuna_id => 92, :provincia_id => 20, :comuna_nombre => "Quinta de Tilcoco"},
	{:comuna_id => 93, :provincia_id => 20, :comuna_nombre => "Rengo"},
	{:comuna_id => 94, :provincia_id => 20, :comuna_nombre => "Requínoa"},
	{:comuna_id => 95, :provincia_id => 20, :comuna_nombre => "San Vicente"},
	{:comuna_id => 96, :provincia_id => 21, :comuna_nombre => "Pichilemu"},
	{:comuna_id => 97, :provincia_id => 21, :comuna_nombre => "La Estrella"},
	{:comuna_id => 98, :provincia_id => 21, :comuna_nombre => "Litueche"},
	{:comuna_id => 99, :provincia_id => 21, :comuna_nombre => "Marchihue"},
	{:comuna_id => 100,:provincia_id => 21, :comuna_nombre => "Navidad"},
	{:comuna_id => 101,:provincia_id => 21, :comuna_nombre => "Paredones"},
	{:comuna_id => 102,:provincia_id => 22, :comuna_nombre => "San Fernando"},
	{:comuna_id => 103,:provincia_id => 22, :comuna_nombre => "Chépica"},
	{:comuna_id => 104,:provincia_id => 22, :comuna_nombre => "Chimbarongo"},
	{:comuna_id => 105,:provincia_id => 22, :comuna_nombre => "Lolol"},
	{:comuna_id => 106,:provincia_id => 22, :comuna_nombre => "Nancagua"},
	{:comuna_id => 107,:provincia_id => 22, :comuna_nombre => "Palmilla"},
	{:comuna_id => 108,:provincia_id => 22, :comuna_nombre => "Peralillo"},
	{:comuna_id => 109,:provincia_id => 22, :comuna_nombre => "Placilla"},
	{:comuna_id => 110,:provincia_id => 22, :comuna_nombre => "Pumanque"},
	{:comuna_id => 111,:provincia_id => 22, :comuna_nombre => "Santa Cruz"},
	{:comuna_id => 112,:provincia_id => 23, :comuna_nombre => "Talca"},
	{:comuna_id => 113,:provincia_id => 23, :comuna_nombre => "Constitución"},
	{:comuna_id => 114,:provincia_id => 23, :comuna_nombre => "Curepto"},
	{:comuna_id => 115,:provincia_id => 23, :comuna_nombre => "Empedrado"},
	{:comuna_id => 116,:provincia_id => 23, :comuna_nombre => "Maule"},
	{:comuna_id => 117,:provincia_id => 23, :comuna_nombre => "Pelarco"},
	{:comuna_id => 118,:provincia_id => 23, :comuna_nombre => "Pencahue"},
	{:comuna_id => 119,:provincia_id => 23, :comuna_nombre => "Río Claro"},
	{:comuna_id => 120,:provincia_id => 23, :comuna_nombre => "San Clemente"},
	{:comuna_id => 121,:provincia_id => 23, :comuna_nombre => "San Rafael"},
	{:comuna_id => 122,:provincia_id => 24, :comuna_nombre => "Cauquenes"},
	{:comuna_id => 123,:provincia_id => 24, :comuna_nombre => "Chanco"},
	{:comuna_id => 124,:provincia_id => 24, :comuna_nombre => "Pelluhue"},
	{:comuna_id => 125,:provincia_id => 25, :comuna_nombre => "Curicó"},
	{:comuna_id => 126,:provincia_id => 25, :comuna_nombre => "Hualañé"},
	{:comuna_id => 127,:provincia_id => 25, :comuna_nombre => "Licantén"},
	{:comuna_id => 128,:provincia_id => 25, :comuna_nombre => "Molina"},
	{:comuna_id => 129,:provincia_id => 25, :comuna_nombre => "Rauco"},
	{:comuna_id => 130,:provincia_id => 25, :comuna_nombre => "Romeral"},
	{:comuna_id => 131,:provincia_id => 25, :comuna_nombre => "Sagrada Familia"},
	{:comuna_id => 132,:provincia_id => 25, :comuna_nombre => "Teno"},
	{:comuna_id => 133,:provincia_id => 25, :comuna_nombre => "Vichuquén"},
	{:comuna_id => 134,:provincia_id => 26, :comuna_nombre => "Linares"},
	{:comuna_id => 135,:provincia_id => 26, :comuna_nombre => "Colbún"},
	{:comuna_id => 136,:provincia_id => 26, :comuna_nombre => "Longaví"},
	{:comuna_id => 137,:provincia_id => 26, :comuna_nombre => "Parral"},
	{:comuna_id => 138,:provincia_id => 26, :comuna_nombre => "Retiro"},
	{:comuna_id => 139,:provincia_id => 26, :comuna_nombre => "San Javier"},
	{:comuna_id => 140,:provincia_id => 26, :comuna_nombre => "Villa Alegre"},
	{:comuna_id => 141,:provincia_id => 26, :comuna_nombre => "Yerbas Buenas"},
	{:comuna_id => 142,:provincia_id => 27, :comuna_nombre => "Concepción"},
	{:comuna_id => 143,:provincia_id => 27, :comuna_nombre => "Coronel"},
	{:comuna_id => 144,:provincia_id => 27, :comuna_nombre => "Chiguayante"},
	{:comuna_id => 145,:provincia_id => 27, :comuna_nombre => "Florida"},
	{:comuna_id => 146,:provincia_id => 27, :comuna_nombre => "Hualqui"},
	{:comuna_id => 147,:provincia_id => 27, :comuna_nombre => "Lota"},
	{:comuna_id => 148,:provincia_id => 27, :comuna_nombre => "Penco"},
	{:comuna_id => 149,:provincia_id => 27, :comuna_nombre => "San Pedro de la Paz"},
	{:comuna_id => 150,:provincia_id => 27, :comuna_nombre => "Santa Juana"},
	{:comuna_id => 151,:provincia_id => 27, :comuna_nombre => "Talcahuano"},
	{:comuna_id => 152,:provincia_id => 27, :comuna_nombre => "Tomé"},
	{:comuna_id => 153,:provincia_id => 27, :comuna_nombre => "Hualpén"},
	{:comuna_id => 154,:provincia_id => 28, :comuna_nombre => "Lebu"},
	{:comuna_id => 155,:provincia_id => 28, :comuna_nombre => "Arauco"},
	{:comuna_id => 156,:provincia_id => 28, :comuna_nombre => "Cañete"},
	{:comuna_id => 157,:provincia_id => 28, :comuna_nombre => "Contulmo"},
	{:comuna_id => 158,:provincia_id => 28, :comuna_nombre => "Curanilahue"},
	{:comuna_id => 159,:provincia_id => 28, :comuna_nombre => "Los Alamos"},
	{:comuna_id => 160,:provincia_id => 28, :comuna_nombre => "Tirúa"},
	{:comuna_id => 161,:provincia_id => 29, :comuna_nombre => "Los Angeles"},
	{:comuna_id => 162,:provincia_id => 29, :comuna_nombre => "Antuco"},
	{:comuna_id => 163,:provincia_id => 29, :comuna_nombre => "Cabrero"},
	{:comuna_id => 164,:provincia_id => 29, :comuna_nombre => "Laja"},
	{:comuna_id => 165,:provincia_id => 29, :comuna_nombre => "Mulchén"},
	{:comuna_id => 166,:provincia_id => 29, :comuna_nombre => "Nacimiento"},
	{:comuna_id => 167,:provincia_id => 29, :comuna_nombre => "Negrete"},
	{:comuna_id => 168,:provincia_id => 29, :comuna_nombre => "Quilaco"},
	{:comuna_id => 169,:provincia_id => 29, :comuna_nombre => "Quilleco"},
	{:comuna_id => 170,:provincia_id => 29, :comuna_nombre => "San Rosendo"},
	{:comuna_id => 171,:provincia_id => 29, :comuna_nombre => "Santa Bárbara"},
	{:comuna_id => 172,:provincia_id => 29, :comuna_nombre => "Tucapel"},
	{:comuna_id => 173,:provincia_id => 29, :comuna_nombre => "Yumbel"},
	{:comuna_id => 174,:provincia_id => 29, :comuna_nombre => "Alto Biobío"},
	{:comuna_id => 175,:provincia_id => 30, :comuna_nombre => "Chillán"},
	{:comuna_id => 176,:provincia_id => 30, :comuna_nombre => "Bulnes"},
	{:comuna_id => 177,:provincia_id => 30, :comuna_nombre => "Cobquecura"},
	{:comuna_id => 178,:provincia_id => 30, :comuna_nombre => "Coelemu"},
	{:comuna_id => 179,:provincia_id => 30, :comuna_nombre => "Coihueco"},
	{:comuna_id => 180,:provincia_id => 30, :comuna_nombre => "Chillán Viejo"},
	{:comuna_id => 181,:provincia_id => 30, :comuna_nombre => "El Carmen"},
	{:comuna_id => 182,:provincia_id => 30, :comuna_nombre => "Ninhue"},
	{:comuna_id => 183,:provincia_id => 30, :comuna_nombre => "Ñiquén"},
	{:comuna_id => 184,:provincia_id => 30, :comuna_nombre => "Pemuco"},
	{:comuna_id => 185,:provincia_id => 30, :comuna_nombre => "Pinto"},
	{:comuna_id => 186,:provincia_id => 30, :comuna_nombre => "Portezuelo"},
	{:comuna_id => 187,:provincia_id => 30, :comuna_nombre => "Quillón"},
	{:comuna_id => 188,:provincia_id => 30, :comuna_nombre => "Quirihue"},
	{:comuna_id => 189,:provincia_id => 30, :comuna_nombre => "Ránquil"},
	{:comuna_id => 190,:provincia_id => 30, :comuna_nombre => "San Carlos"},
	{:comuna_id => 191,:provincia_id => 30, :comuna_nombre => "San Fabián"},
	{:comuna_id => 192,:provincia_id => 30, :comuna_nombre => "San Ignacio"},
	{:comuna_id => 193,:provincia_id => 30, :comuna_nombre => "San Nicolás"},
	{:comuna_id => 194,:provincia_id => 30, :comuna_nombre => "Treguaco"},
	{:comuna_id => 195,:provincia_id => 30, :comuna_nombre => "Yungay"},
	{:comuna_id => 196,:provincia_id => 31, :comuna_nombre => "Temuco"},
	{:comuna_id => 197,:provincia_id => 31, :comuna_nombre => "Carahue"},
	{:comuna_id => 198,:provincia_id => 31, :comuna_nombre => "Cunco"},
	{:comuna_id => 199,:provincia_id => 31, :comuna_nombre => "Curarrehue"},
	{:comuna_id => 200,:provincia_id => 31, :comuna_nombre => "Freire"},
	{:comuna_id => 201,:provincia_id => 31, :comuna_nombre => "Galvarino"},
	{:comuna_id => 202,:provincia_id => 31, :comuna_nombre => "Gorbea"},
	{:comuna_id => 203,:provincia_id => 31, :comuna_nombre => "Lautaro"},
	{:comuna_id => 204,:provincia_id => 31, :comuna_nombre => "Loncoche"},
	{:comuna_id => 205,:provincia_id => 31, :comuna_nombre => "Melipeuco"},
	{:comuna_id => 206,:provincia_id => 31, :comuna_nombre => "Nueva Imperial"},
	{:comuna_id => 207,:provincia_id => 31, :comuna_nombre => "Padre Las Casas"},
	{:comuna_id => 208,:provincia_id => 31, :comuna_nombre => "Perquenco"},
	{:comuna_id => 209,:provincia_id => 31, :comuna_nombre => "Pitrufquén"},
	{:comuna_id => 210,:provincia_id => 31, :comuna_nombre => "Pucón"},
	{:comuna_id => 211,:provincia_id => 31, :comuna_nombre => "Saavedra"},
	{:comuna_id => 212,:provincia_id => 31, :comuna_nombre => "Teodoro Schmidt"},
	{:comuna_id => 213,:provincia_id => 31, :comuna_nombre => "Toltén"},
	{:comuna_id => 214,:provincia_id => 31, :comuna_nombre => "Vilcún"},
	{:comuna_id => 215,:provincia_id => 31, :comuna_nombre => "Villarrica"},
	{:comuna_id => 216,:provincia_id => 31, :comuna_nombre => "Cholchol"},
	{:comuna_id => 217,:provincia_id => 32, :comuna_nombre => "Angol"},
	{:comuna_id => 218,:provincia_id => 32, :comuna_nombre => "Collipulli"},
	{:comuna_id => 219,:provincia_id => 32, :comuna_nombre => "Curacautín"},
	{:comuna_id => 220,:provincia_id => 32, :comuna_nombre => "Ercilla"},
	{:comuna_id => 221,:provincia_id => 32, :comuna_nombre => "Lonquimay"},
	{:comuna_id => 222,:provincia_id => 32, :comuna_nombre => "Los Sauces"},
	{:comuna_id => 223,:provincia_id => 32, :comuna_nombre => "Lumaco"},
	{:comuna_id => 224,:provincia_id => 32, :comuna_nombre => "Purén"},
	{:comuna_id => 225,:provincia_id => 32, :comuna_nombre => "Renaico"},
	{:comuna_id => 226,:provincia_id => 32, :comuna_nombre => "Traiguén"},
	{:comuna_id => 227,:provincia_id => 32, :comuna_nombre => "Victoria"},
	{:comuna_id => 228,:provincia_id => 33, :comuna_nombre => "Valdivia"},
	{:comuna_id => 229,:provincia_id => 33, :comuna_nombre => "Corral"},
	{:comuna_id => 230,:provincia_id => 33, :comuna_nombre => "Lanco"},
	{:comuna_id => 231,:provincia_id => 33, :comuna_nombre => "Los Lagos"},
	{:comuna_id => 232,:provincia_id => 33, :comuna_nombre => "Máfil"},
	{:comuna_id => 233,:provincia_id => 33, :comuna_nombre => "Mariquina"},
	{:comuna_id => 234,:provincia_id => 33, :comuna_nombre => "Paillaco"},
	{:comuna_id => 235,:provincia_id => 33, :comuna_nombre => "Panguipulli"},
	{:comuna_id => 236,:provincia_id => 34, :comuna_nombre => "La Unión"},
	{:comuna_id => 237,:provincia_id => 34, :comuna_nombre => "Futrono"},
	{:comuna_id => 238,:provincia_id => 34, :comuna_nombre => "Lago Ranco"},
	{:comuna_id => 239,:provincia_id => 34, :comuna_nombre => "Río Bueno"},
	{:comuna_id => 240,:provincia_id => 35, :comuna_nombre => "Puerto Montt"},
	{:comuna_id => 241,:provincia_id => 35, :comuna_nombre => "Calbuco"},
	{:comuna_id => 242,:provincia_id => 35, :comuna_nombre => "Cochamó"},
	{:comuna_id => 243,:provincia_id => 35, :comuna_nombre => "Fresia"},
	{:comuna_id => 244,:provincia_id => 35, :comuna_nombre => "Frutillar"},
	{:comuna_id => 245,:provincia_id => 35, :comuna_nombre => "Los Muermos"},
	{:comuna_id => 246,:provincia_id => 35, :comuna_nombre => "Llanquihue"},
	{:comuna_id => 247,:provincia_id => 35, :comuna_nombre => "Maullín"},
	{:comuna_id => 248,:provincia_id => 35, :comuna_nombre => "Puerto Var"},
	{:comuna_id => 249,:provincia_id => 36, :comuna_nombre => "Castro"},
	{:comuna_id => 250,:provincia_id => 36, :comuna_nombre => "Ancud"},
	{:comuna_id => 251,:provincia_id => 36, :comuna_nombre => "Chonchi"},
	{:comuna_id => 252,:provincia_id => 36, :comuna_nombre => "Curaco de Vélez"},
	{:comuna_id => 253,:provincia_id => 36, :comuna_nombre => "Dalcahue"},
	{:comuna_id => 254,:provincia_id => 36, :comuna_nombre => "Puqueldón"},
	{:comuna_id => 255,:provincia_id => 36, :comuna_nombre => "Queilén"},
	{:comuna_id => 256,:provincia_id => 36, :comuna_nombre => "Quellón"},
	{:comuna_id => 257,:provincia_id => 36, :comuna_nombre => "Quemchi"},
	{:comuna_id => 258,:provincia_id => 36, :comuna_nombre => "Quinchao"},
	{:comuna_id => 259,:provincia_id => 37, :comuna_nombre => "Osorno"},
	{:comuna_id => 260,:provincia_id => 37, :comuna_nombre => "Puerto Octay"},
	{:comuna_id => 261,:provincia_id => 37, :comuna_nombre => "Purranque"},
	{:comuna_id => 262,:provincia_id => 37, :comuna_nombre => "Puyehue"},
	{:comuna_id => 263,:provincia_id => 37, :comuna_nombre => "Río Negro"},
	{:comuna_id => 264,:provincia_id => 37, :comuna_nombre => "San Juan de la Costa"},
	{:comuna_id => 265,:provincia_id => 37, :comuna_nombre => "San Pablo"},
	{:comuna_id => 266,:provincia_id => 38, :comuna_nombre => "Chaitén"},
	{:comuna_id => 267,:provincia_id => 38, :comuna_nombre => "Futaleufú"},
	{:comuna_id => 268,:provincia_id => 38, :comuna_nombre => "Hualaihué"},
	{:comuna_id => 269,:provincia_id => 38, :comuna_nombre => "Palena"},
	{:comuna_id => 270,:provincia_id => 39, :comuna_nombre => "Coihaique"},
	{:comuna_id => 271,:provincia_id => 39, :comuna_nombre => "Lago Verde"},
	{:comuna_id => 272,:provincia_id => 40, :comuna_nombre => "Aisén"},
	{:comuna_id => 273,:provincia_id => 40, :comuna_nombre => "Cisnes"},
	{:comuna_id => 274,:provincia_id => 40, :comuna_nombre => "Guaitecas"},
	{:comuna_id => 275,:provincia_id => 41, :comuna_nombre => "Cochrane"},
	{:comuna_id => 276,:provincia_id => 41, :comuna_nombre => "O\'Higgins"},
	{:comuna_id => 277,:provincia_id => 41, :comuna_nombre => "Tortel"},
	{:comuna_id => 278,:provincia_id => 42, :comuna_nombre => "Chile Chico"},
	{:comuna_id => 279,:provincia_id => 42, :comuna_nombre => "Río Ibáñez"},
	{:comuna_id => 280,:provincia_id => 43, :comuna_nombre => "Punta Arenas"},
	{:comuna_id => 281,:provincia_id => 43, :comuna_nombre => "Laguna Blanca"},
	{:comuna_id => 282,:provincia_id => 43, :comuna_nombre => "Río Verde"},
	{:comuna_id => 283,:provincia_id => 43, :comuna_nombre => "San Gregorio"},
	{:comuna_id => 284,:provincia_id => 44, :comuna_nombre => "Cabo de Hornos (Ex-Navarino)"},
	{:comuna_id => 285,:provincia_id => 44, :comuna_nombre => "Antártica"},
	{:comuna_id => 286,:provincia_id => 45, :comuna_nombre => "Porvenir"},
	{:comuna_id => 287,:provincia_id => 45, :comuna_nombre => "Primavera"},
	{:comuna_id => 288,:provincia_id => 45, :comuna_nombre => "Timaukel"},
	{:comuna_id => 289,:provincia_id => 46, :comuna_nombre => "Natales"},
	{:comuna_id => 290,:provincia_id => 46, :comuna_nombre => "Torres del Paine"},
	{:comuna_id => 291,:provincia_id => 47, :comuna_nombre => "Santiago"},
	{:comuna_id => 292,:provincia_id => 47, :comuna_nombre => "Cerrillos"},
	{:comuna_id => 293,:provincia_id => 47, :comuna_nombre => "Cerro Navia"},
	{:comuna_id => 294,:provincia_id => 47, :comuna_nombre => "Conchalí"},
	{:comuna_id => 295,:provincia_id => 47, :comuna_nombre => "El Bosque"},
	{:comuna_id => 296,:provincia_id => 47, :comuna_nombre => "Estación Central"},
	{:comuna_id => 297,:provincia_id => 47, :comuna_nombre => "Huechuraba"},
	{:comuna_id => 298,:provincia_id => 47, :comuna_nombre => "Independencia"},
	{:comuna_id => 299,:provincia_id => 47, :comuna_nombre => "La Cisterna"},
	{:comuna_id => 300,:provincia_id => 47, :comuna_nombre => "La Florida"},
	{:comuna_id => 301,:provincia_id => 47, :comuna_nombre => "La Granja"},
	{:comuna_id => 302,:provincia_id => 47, :comuna_nombre => "La Pintana"},
	{:comuna_id => 303,:provincia_id => 47, :comuna_nombre => "La Reina"},
	{:comuna_id => 304,:provincia_id => 47, :comuna_nombre => "Las Condes"},
	{:comuna_id => 305,:provincia_id => 47, :comuna_nombre => "Lo Barnechea"},
	{:comuna_id => 306,:provincia_id => 47, :comuna_nombre => "Lo Espejo"},
	{:comuna_id => 307,:provincia_id => 47, :comuna_nombre => "Lo Prado"},
	{:comuna_id => 308,:provincia_id => 47, :comuna_nombre => "Macul"},
	{:comuna_id => 309,:provincia_id => 47, :comuna_nombre => "Maipú"},
	{:comuna_id => 310,:provincia_id => 47, :comuna_nombre => "Ñuñoa"},
	{:comuna_id => 311,:provincia_id => 47, :comuna_nombre => "Pedro Aguirre Cerda"},
	{:comuna_id => 312,:provincia_id => 47, :comuna_nombre => "Peñalolén"},
	{:comuna_id => 313,:provincia_id => 47, :comuna_nombre => "Providencia"},
	{:comuna_id => 314,:provincia_id => 47, :comuna_nombre => "Pudahuel"},
	{:comuna_id => 315,:provincia_id => 47, :comuna_nombre => "Quilicura"},
	{:comuna_id => 316,:provincia_id => 47, :comuna_nombre => "Quinta Normal"},
	{:comuna_id => 317,:provincia_id => 47, :comuna_nombre => "Recoleta"},
	{:comuna_id => 318,:provincia_id => 47, :comuna_nombre => "Renca"},
	{:comuna_id => 319,:provincia_id => 47, :comuna_nombre => "San Joaquín"},
	{:comuna_id => 320,:provincia_id => 47, :comuna_nombre => "San Miguel"},
	{:comuna_id => 321,:provincia_id => 47, :comuna_nombre => "San Ramón"},
	{:comuna_id => 322,:provincia_id => 47, :comuna_nombre => "Vitacura"},
	{:comuna_id => 323,:provincia_id => 48, :comuna_nombre => "Puente Alto"},
	{:comuna_id => 324,:provincia_id => 48, :comuna_nombre => "Pirque"},
	{:comuna_id => 325,:provincia_id => 48, :comuna_nombre => "San José de Maipo"},
	{:comuna_id => 326,:provincia_id => 49, :comuna_nombre => "Colina"},
	{:comuna_id => 327,:provincia_id => 49, :comuna_nombre => "Lampa"},
	{:comuna_id => 328,:provincia_id => 49, :comuna_nombre => "Tiltil"},
	{:comuna_id => 329,:provincia_id => 50, :comuna_nombre => "San Bernardo"},
	{:comuna_id => 330,:provincia_id => 50, :comuna_nombre => "Buin"},
	{:comuna_id => 331,:provincia_id => 50, :comuna_nombre => "Calera de Tango"},
	{:comuna_id => 332,:provincia_id => 50, :comuna_nombre => "Paine"},
	{:comuna_id => 333,:provincia_id => 51, :comuna_nombre => "Melipilla"},
	{:comuna_id => 334,:provincia_id => 51, :comuna_nombre => "Alhué"},
	{:comuna_id => 335,:provincia_id => 51, :comuna_nombre => "Curacaví"},
	{:comuna_id => 336,:provincia_id => 51, :comuna_nombre => "María Pinto"},
	{:comuna_id => 337,:provincia_id => 51, :comuna_nombre => "San Pedro"},
	{:comuna_id => 338,:provincia_id => 52, :comuna_nombre => "Talagante"},
	{:comuna_id => 339,:provincia_id => 52, :comuna_nombre => "El Monte"},
	{:comuna_id => 340,:provincia_id => 52, :comuna_nombre => "Isla de Maipo"},
	{:comuna_id => 341,:provincia_id => 52, :comuna_nombre => "Padre Hurtado"},
    {:comuna_id => 342,:provincia_id => 52, :comuna_nombre => "Peñaflor"},
	{:comuna_id => 343,:provincia_id => 53, :comuna_nombre => "Arica"},
	{:comuna_id => 344,:provincia_id => 53, :comuna_nombre => "Camarones"},
	{:comuna_id => 345,:provincia_id => 54, :comuna_nombre => "Putre"},
	{:comuna_id => 346,:provincia_id => 54, :comuna_nombre => "General Lagos"},
].each do |comuna|
	Comuna.find_or_create_by(comuna)
end


[
	{:clase_id => 1,  :cla_clase_id => NULL, :clase_nombre => "Accesorios para Vehículos"},
	{:clase_id => 2,  :cla_clase_id => 1, :clase_nombre => "Accesorios para Vehículos"},
	{:clase_id => 3,  :cla_clase_id => 2, :clase_nombre => "Asientos"},
	{:clase_id => 4,  :cla_clase_id => 2, :clase_nombre => "Aspiradoras Portátiles"},
	{:clase_id => 5,  :cla_clase_id => 2, :clase_nombre => "Autoadhesivos y Gráfica"},
	{:clase_id => 6,  :cla_clase_id => 2, :clase_nombre => "Cubre Asientos"},
	{:clase_id => 7,  :cla_clase_id => 2, :clase_nombre => "Cubre Ruedas"},
	{:clase_id => 8,  :cla_clase_id => 2, :clase_nombre => "Economizadores de Combustible"},
	{:clase_id => 9,  :cla_clase_id => 2, :clase_nombre => "Focos"},
	{:clase_id => 10,  :cla_clase_id => 2, :clase_nombre => "Insignias"},
	{:clase_id => 11,  :cla_clase_id => 2, :clase_nombre => "Inversores de Voltaje"},
	{:clase_id => 12,  :cla_clase_id => 2, :clase_nombre => "Manillas"},
	{:clase_id => 13,  :cla_clase_id => 2, :clase_nombre => "Palancas de Cambios"},
	{:clase_id => 14,  :cla_clase_id => 2, :clase_nombre => "Pedales"},
	{:clase_id => 15,  :cla_clase_id => 2, :clase_nombre => "Pisos"},
	{:clase_id => 16,  :cla_clase_id => 2, :clase_nombre => "Portabicicletas"},
	{:clase_id => 17,  :cla_clase_id => 2, :clase_nombre => "Scanners para Automóviles"},
	{:clase_id => 18,  :cla_clase_id => 2, :clase_nombre => "Tableros"},
	{:clase_id => 19,  :cla_clase_id => 2, :clase_nombre => "Volantes"},
	{:clase_id => 20,  :cla_clase_id => 2, :clase_nombre => "Otros Accesorios"},
	{:clase_id => 21,  :cla_clase_id => 1, :clase_nombre => "Accesorios y Repuestos Motos"},
	{:clase_id => 22,  :cla_clase_id => 21, :clase_nombre => "Antiparras"},
	{:clase_id => 23,  :cla_clase_id => 21, :clase_nombre => "Cascos"},
	{:clase_id => 24,  :cla_clase_id => 21, :clase_nombre => "Fundas"},
	{:clase_id => 25,  :cla_clase_id => 21, :clase_nombre => "Guantes"},
	{:clase_id => 26,  :cla_clase_id => 21, :clase_nombre => "Maletas"},
	{:clase_id => 27,  :cla_clase_id => 21, :clase_nombre => "Manuales"},
	{:clase_id => 28,  :cla_clase_id => 21, :clase_nombre => "Neumáticos"},
	{:clase_id => 29,  :cla_clase_id => 21, :clase_nombre => "Repuestos"},
	{:clase_id => 30,  :cla_clase_id => 21, :clase_nombre => "Seguridad"},
	{:clase_id => 31,  :cla_clase_id => 21, :clase_nombre => "Vestuario"},
	{:clase_id => 32,  :cla_clase_id => 21, :clase_nombre => "Otros"},
	{:clase_id => 33,  :cla_clase_id => 1, :clase_nombre => "Alerones, Spoilers y Faldones"},
	{:clase_id => 34,  :cla_clase_id => 33, :clase_nombre => "Alerones"},
	{:clase_id => 35,  :cla_clase_id => 33, :clase_nombre => "Faldones"},
	{:clase_id => 36,  :cla_clase_id => 33, :clase_nombre => "Spoilers"},
	{:clase_id => 37,  :cla_clase_id => 33, :clase_nombre => "Otros"},
	{:clase_id => 38,  :cla_clase_id => 1, :clase_nombre => "Audio para Vehículos"},
	{:clase_id => 39,  :cla_clase_id => 38, :clase_nombre => "Amplificadores"},
	{:clase_id => 40,  :cla_clase_id => 38, :clase_nombre => "Cables y Conectores"},
	{:clase_id => 41,  :cla_clase_id => 38, :clase_nombre => "Cajas Acústicas"},
	{:clase_id => 42,  :cla_clase_id => 38, :clase_nombre => "Capacitadores"},
	{:clase_id => 43,  :cla_clase_id => 38, :clase_nombre => "Controles Remotos"},
	{:clase_id => 44,  :cla_clase_id => 38, :clase_nombre => "Parlantes"},
	{:clase_id => 45,  :cla_clase_id => 38, :clase_nombre => "Radios con CD"},
	{:clase_id => 46,  :cla_clase_id => 38, :clase_nombre => "Radios con DVD y Pantallas"},
	{:clase_id => 47,  :cla_clase_id => 38, :clase_nombre => "Radios con Entrada USB"},
	{:clase_id => 48,  :cla_clase_id => 38, :clase_nombre => "Radios con MP3"},
	{:clase_id => 49,  :cla_clase_id => 38, :clase_nombre => "Subwoofers"},
	{:clase_id => 50,  :cla_clase_id => 38, :clase_nombre => "Transmisores de FM"},
	{:clase_id => 51,  :cla_clase_id => 38, :clase_nombre => "Otros"},
	{:clase_id => 52,  :cla_clase_id => 1, :clase_nombre => "GPS"},
	{:clase_id => 53,  :cla_clase_id => 52, :clase_nombre => "Equipos"},
	{:clase_id => 54,  :cla_clase_id => 52, :clase_nombre => "Mapas y Accesorios"},
	{:clase_id => 55,  :cla_clase_id => 52, :clase_nombre => "Otros"},
	{:clase_id => 56,  :cla_clase_id => 1, :clase_nombre => "Iluminación para Vehículos"},
	{:clase_id => 57,  :cla_clase_id => 56, :clase_nombre => "Ampolletas"},
	{:clase_id => 58,  :cla_clase_id => 56, :clase_nombre => "Angel Eyes"},
	{:clase_id => 59,  :cla_clase_id => 56, :clase_nombre => "Neblineros"},
	{:clase_id => 60,  :cla_clase_id => 56, :clase_nombre => "Ópticas Delanteras"},
	{:clase_id => 61,  :cla_clase_id => 56, :clase_nombre => "Traseros"},
	{:clase_id => 62,  :cla_clase_id => 56, :clase_nombre => "Xenon"},
	{:clase_id => 63,  :cla_clase_id => 56, :clase_nombre => "Otros"},
	{:clase_id => 64,  :cla_clase_id => 1, :clase_nombre => "Llantas, Neumáticos y Tapas"},
	{:clase_id => 65,  :cla_clase_id => 64, :clase_nombre => "Llantas"},
	{:clase_id => 66,  :cla_clase_id => 64, :clase_nombre => "Neumáticos"},
	{:clase_id => 67,  :cla_clase_id => 64, :clase_nombre => "Tapas de Rueda"},
	{:clase_id => 68,  :cla_clase_id => 64, :clase_nombre => "Otros"},
	{:clase_id => 69,  :cla_clase_id => 1, :clase_nombre => "Manuales de Vehículos"},
	{:clase_id => 70,  :cla_clase_id => 69, :clase_nombre => "Alfa Romeo"},
	{:clase_id => 71,  :cla_clase_id => 69, :clase_nombre => "Audi"},
	{:clase_id => 72,  :cla_clase_id => 69, :clase_nombre => "BMW"},
	{:clase_id => 73,  :cla_clase_id => 69, :clase_nombre => "Chevrolet"},
	{:clase_id => 74,  :cla_clase_id => 69, :clase_nombre => "Chrysler"},
	{:clase_id => 75,  :cla_clase_id => 69, :clase_nombre => "Citroën"},
	{:clase_id => 76,  :cla_clase_id => 69, :clase_nombre => "Daewoo"},
	{:clase_id => 77,  :cla_clase_id => 69, :clase_nombre => "Dodge"},
	{:clase_id => 78,  :cla_clase_id => 69, :clase_nombre => "Fiat"},
	{:clase_id => 79,  :cla_clase_id => 69, :clase_nombre => "Ford"},
	{:clase_id => 80,  :cla_clase_id => 69, :clase_nombre => "Honda"},
	{:clase_id => 81,  :cla_clase_id => 69, :clase_nombre => "Hyundai"},
	{:clase_id => 82,  :cla_clase_id => 69, :clase_nombre => "Jeep"},
	{:clase_id => 83,  :cla_clase_id => 69, :clase_nombre => "Kia"},
	{:clase_id => 84,  :cla_clase_id => 69, :clase_nombre => "Mazda"},
	{:clase_id => 85,  :cla_clase_id => 69, :clase_nombre => "Mercedes Benz"},
	{:clase_id => 86,  :cla_clase_id => 69, :clase_nombre => "Mitsubishi"},
	{:clase_id => 87,  :cla_clase_id => 69, :clase_nombre => "Nissan"},
	{:clase_id => 88,  :cla_clase_id => 69, :clase_nombre => "Peugeot"},
	{:clase_id => 89,  :cla_clase_id => 69, :clase_nombre => "Renault"},
	{:clase_id => 90,  :cla_clase_id => 69, :clase_nombre => "Rover"},
	{:clase_id => 91,  :cla_clase_id => 69, :clase_nombre => "Subaru"},
	{:clase_id => 92,  :cla_clase_id => 69, :clase_nombre => "Suzuki"},
	{:clase_id => 93,  :cla_clase_id => 69, :clase_nombre => "Toyota"},
	{:clase_id => 94,  :cla_clase_id => 69, :clase_nombre => "Volkswagen"},
	{:clase_id => 95,  :cla_clase_id => 69, :clase_nombre => "Volvo"},
	{:clase_id => 96,  :cla_clase_id => 69, :clase_nombre => "Otros"},
	{:clase_id => 97,  :cla_clase_id => 1, :clase_nombre => "Otros"},
	{:clase_id => 98,  :cla_clase_id => 1, :clase_nombre => "Repuestos para Vehículos"},
	{:clase_id => 99,  :cla_clase_id => 98, :clase_nombre => "Amortiguadores y Espirales"},
	{:clase_id => 100,  :cla_clase_id => 98, :clase_nombre => "Bobinas"},
	{:clase_id => 101,  :cla_clase_id => 98, :clase_nombre => "Bujías"},
	{:clase_id => 102,  :cla_clase_id => 98, :clase_nombre => "Butacas"},
	{:clase_id => 103,  :cla_clase_id => 98, :clase_nombre => "Cajas de Cambios"},
	{:clase_id => 104,  :cla_clase_id => 98, :clase_nombre => "Computadores"},
	{:clase_id => 105,  :cla_clase_id => 98, :clase_nombre => "Culatas"},
	{:clase_id => 106,  :cla_clase_id => 98, :clase_nombre => "Emblemas e Insignias"},
	{:clase_id => 107,  :cla_clase_id => 98, :clase_nombre => "Escapes"},
	{:clase_id => 108,  :cla_clase_id => 98, :clase_nombre => "Espejos para Vehículos"},
	{:clase_id => 109,  :cla_clase_id => 98, :clase_nombre => "Filtros"},
	{:clase_id => 110,  :cla_clase_id => 98, :clase_nombre => "Máscaras"},
	{:clase_id => 111,  :cla_clase_id => 98, :clase_nombre => "Motores"},
	{:clase_id => 112,  :cla_clase_id => 98, :clase_nombre => "Parachoques"},
	{:clase_id => 113,  :cla_clase_id => 98, :clase_nombre => "Parrillas para Vehículos"},
	{:clase_id => 114,  :cla_clase_id => 98, :clase_nombre => "Pastillas"},
	{:clase_id => 115,  :cla_clase_id => 98, :clase_nombre => "Otros"},
	{:clase_id => 116,  :cla_clase_id => 1, :clase_nombre => "Repuestos y Acc. Camionetas"},
	{:clase_id => 117,  :cla_clase_id => 116, :clase_nombre => "Accesorios"},
	{:clase_id => 118,  :cla_clase_id => 116, :clase_nombre => "Repuestos"},
	{:clase_id => 119,  :cla_clase_id => 116, :clase_nombre => "Otros"},
	{:clase_id => 120,  :cla_clase_id => 1, :clase_nombre => "Seguridad para Vehículos"},
	{:clase_id => 121,  :cla_clase_id => 120, :clase_nombre => "Alarmas"},
	{:clase_id => 122,  :cla_clase_id => 120, :clase_nombre => "Kits - Alarma y Cierre"},
	{:clase_id => 123,  :cla_clase_id => 120, :clase_nombre => "Sensores de Retroceso"},
	{:clase_id => 124,  :cla_clase_id => 120, :clase_nombre => "Vidrios y Cierre Centralizado"},
	{:clase_id => 125,  :cla_clase_id => 120, :clase_nombre => "Otros"},
	{:clase_id => 126,  :cla_clase_id => NULL, :clase_nombre => "Animales y Mascotas"},
	{:clase_id => 127,  :cla_clase_id => 126, :clase_nombre => "Aves"},
	{:clase_id => 128,  :cla_clase_id => 127, :clase_nombre => "Alimentos"},
	{:clase_id => 129,  :cla_clase_id => 127, :clase_nombre => "Aves"},
	{:clase_id => 130,  :cla_clase_id => 127, :clase_nombre => "Comedores y Bebederos"},
	{:clase_id => 131,  :cla_clase_id => 127, :clase_nombre => "Incubadoras"},
	{:clase_id => 132,  :cla_clase_id => 127, :clase_nombre => "Jaulas y Accesorios"},
	{:clase_id => 133,  :cla_clase_id => 127, :clase_nombre => "Otros"},
	{:clase_id => 134,  :cla_clase_id => 126, :clase_nombre => "Caballos"},
	{:clase_id => 135,  :cla_clase_id => 134, :clase_nombre => "Accesorios para Montar"},
	{:clase_id => 136,  :cla_clase_id => 134, :clase_nombre => "Caballos"},
	{:clase_id => 137,  :cla_clase_id => 134, :clase_nombre => "Otros"},
	{:clase_id => 138,  :cla_clase_id => 126, :clase_nombre => "Gatos"},
	{:clase_id => 139,  :cla_clase_id => 138, :clase_nombre => "Accesorios"},
	{:clase_id => 140,  :cla_clase_id => 138, :clase_nombre => "Alimentos"},
	{:clase_id => 141,  :cla_clase_id => 138, :clase_nombre => "Arena Sanitaria"},
	{:clase_id => 142,  :cla_clase_id => 138, :clase_nombre => "Camas, Iglús y Colchonetas"},
	{:clase_id => 143,  :cla_clase_id => 138, :clase_nombre => "Estética y Cuidado"},
	{:clase_id => 144,  :cla_clase_id => 138, :clase_nombre => "Gatos"},
	{:clase_id => 145,  :cla_clase_id => 138, :clase_nombre => "Transportadoras"},
	{:clase_id => 146,  :cla_clase_id => 138, :clase_nombre => "Otros"},
	{:clase_id => 147,  :cla_clase_id => 126, :clase_nombre => "Peces"},
	{:clase_id => 148,  :cla_clase_id => 147, :clase_nombre => "Accesorios para Acuarios"},
	{:clase_id => 149,  :cla_clase_id => 147, :clase_nombre => "Acuarios"},
	{:clase_id => 150,  :cla_clase_id => 147, :clase_nombre => "Alimentos para Peces"},
	{:clase_id => 151,  :cla_clase_id => 147, :clase_nombre => "Peces"},
	{:clase_id => 152,  :cla_clase_id => 147, :clase_nombre => "Otros"},
	{:clase_id => 153,  :cla_clase_id => 126, :clase_nombre => "Perros"},
	{:clase_id => 154,  :cla_clase_id => 153, :clase_nombre => "Alimentos"},
	{:clase_id => 155,  :cla_clase_id => 153, :clase_nombre => "Artículos para Adistramiento"},
	{:clase_id => 156,  :cla_clase_id => 153, :clase_nombre => "Cachorros"},
	{:clase_id => 157,  :cla_clase_id => 153, :clase_nombre => "Camas para Perro"},
	{:clase_id => 158,  :cla_clase_id => 153, :clase_nombre => "Collares, Correas y Arneses"},
	{:clase_id => 159,  :cla_clase_id => 153, :clase_nombre => "Estética y Cuidado"},
	{:clase_id => 160,  :cla_clase_id => 153, :clase_nombre => "Juguetes"},
	{:clase_id => 161,  :cla_clase_id => 153, :clase_nombre => "Perros para Cruza"},
	{:clase_id => 162,  :cla_clase_id => 153, :clase_nombre => "Ropa para Perros"},
	{:clase_id => 163,  :cla_clase_id => 153, :clase_nombre => "Transportadoras y Casas"},
	{:clase_id => 164,  :cla_clase_id => 153, :clase_nombre => "Otros"},
	{:clase_id => 165,  :cla_clase_id => 126, :clase_nombre => "Roedores"},
	{:clase_id => 166,  :cla_clase_id => 165, :clase_nombre => "Accesorios"},
	{:clase_id => 167,  :cla_clase_id => 165, :clase_nombre => "Jaulas y Hábitats"},
	{:clase_id => 168,  :cla_clase_id => 165, :clase_nombre => "Roedores"},
	{:clase_id => 169,  :cla_clase_id => 165, :clase_nombre => "Otros"},
	{:clase_id => 170,  :cla_clase_id => 126, :clase_nombre => "Otros"},
	{:clase_id => 171,  :cla_clase_id => NULL, :clase_nombre => "Bebés"},
	{:clase_id => 172,  :cla_clase_id => 171, :clase_nombre => "Alimentación para Bebés"},
	{:clase_id => 173,  :cla_clase_id => 172, :clase_nombre => "Baberos"},
	{:clase_id => 174,  :cla_clase_id => 172, :clase_nombre => "Calentadores de Mamaderas"},
	{:clase_id => 175,  :cla_clase_id => 172, :clase_nombre => "Cojines de Lactancia"},
	{:clase_id => 176,  :cla_clase_id => 172, :clase_nombre => "Esterilizadores"},
	{:clase_id => 177,  :cla_clase_id => 172, :clase_nombre => "Leches"},
	{:clase_id => 178,  :cla_clase_id => 172, :clase_nombre => "Mamaderas"},
	{:clase_id => 179,  :cla_clase_id => 172, :clase_nombre => "Sacaleches"},
	{:clase_id => 180,  :cla_clase_id => 172, :clase_nombre => "Otros"},
	{:clase_id => 181,  :cla_clase_id => 171, :clase_nombre => "Andadores y Correpasillos"},
	{:clase_id => 182,  :cla_clase_id => 181, :clase_nombre => "Andadores"},
	{:clase_id => 183,  :cla_clase_id => 181, :clase_nombre => "Correpasillos"},
	{:clase_id => 184,  :cla_clase_id => 181, :clase_nombre => "Otros"},
	{:clase_id => 185,  :cla_clase_id => 171, :clase_nombre => "Artículos de Bebés para Baños"},
	{:clase_id => 186,  :cla_clase_id => 185, :clase_nombre => "Artículos de Tocador"},
	{:clase_id => 187,  :cla_clase_id => 185, :clase_nombre => "Bañeras"},
	{:clase_id => 188,  :cla_clase_id => 185, :clase_nombre => "Hamacas"},
	{:clase_id => 189,  :cla_clase_id => 185, :clase_nombre => "Pelelas"},
	{:clase_id => 190,  :cla_clase_id => 185, :clase_nombre => "Otros"},
	{:clase_id => 191,  :cla_clase_id => 171, :clase_nombre => "Artículos para Futuras Mamás"},
	{:clase_id => 192,  :cla_clase_id => 191, :clase_nombre => "Accesorios"},
	{:clase_id => 193,  :cla_clase_id => 191, :clase_nombre => "Vestuario"},
	{:clase_id => 194,  :cla_clase_id => 191, :clase_nombre => "Otros"},
	{:clase_id => 195,  :cla_clase_id => 171, :clase_nombre => "Bolsos"},
	{:clase_id => 196,  :cla_clase_id => 171, :clase_nombre => "Coches de Bebés"},
	{:clase_id => 197,  :cla_clase_id => 196, :clase_nombre => "Coches Paseo"},
	{:clase_id => 198,  :cla_clase_id => 196, :clase_nombre => "Mellizos"},
	{:clase_id => 199,  :cla_clase_id => 196, :clase_nombre => "Paraguas"},
	{:clase_id => 200,  :cla_clase_id => 196, :clase_nombre => "Travel System"},
	{:clase_id => 201,  :cla_clase_id => 196, :clase_nombre => "Otros"},
	{:clase_id => 202,  :cla_clase_id => 171, :clase_nombre => "Cuarto de Bebé"},
	{:clase_id => 203,  :cla_clase_id => 202, :clase_nombre => "Cunas Corral"},
	{:clase_id => 204,  :cla_clase_id => 202, :clase_nombre => "Cunas de Madera"},
	{:clase_id => 205,  :cla_clase_id => 202, :clase_nombre => "Moisés"},
	{:clase_id => 206,  :cla_clase_id => 202, :clase_nombre => "Ropa de Cuna"},
	{:clase_id => 207,  :cla_clase_id => 202, :clase_nombre => "Otros"},
	{:clase_id => 208,  :cla_clase_id => 171, :clase_nombre => "Juguetes para Bebés"},
	{:clase_id => 209,  :cla_clase_id => 208, :clase_nombre => "Columpios y Mecedoras"},
	{:clase_id => 210,  :cla_clase_id => 208, :clase_nombre => "Gimnasios y Activity Centers"},
	{:clase_id => 211,  :cla_clase_id => 208, :clase_nombre => "Juegos Didácticos"},
	{:clase_id => 212,  :cla_clase_id => 208, :clase_nombre => "Musicales"},
	{:clase_id => 213,  :cla_clase_id => 208, :clase_nombre => "Muñecos y Peluches"},
	{:clase_id => 214,  :cla_clase_id => 208, :clase_nombre => "Otros"},
	{:clase_id => 215,  :cla_clase_id => 171, :clase_nombre => "Otros"},
	{:clase_id => 216,  :cla_clase_id => 171, :clase_nombre => "Películas Infantiles"},
	{:clase_id => 217,  :cla_clase_id => 216, :clase_nombre => "DVD"},
	{:clase_id => 218,  :cla_clase_id => 216, :clase_nombre => "VHS"},
	{:clase_id => 219,  :cla_clase_id => 216, :clase_nombre => "Otros Formatos"},
	{:clase_id => 220,  :cla_clase_id => 171, :clase_nombre => "Porta Bebés"},
	{:clase_id => 221,  :cla_clase_id => 171, :clase_nombre => "Seguridad para Bebés"},
	{:clase_id => 222,  :cla_clase_id => 221, :clase_nombre => "Barandas"},
	{:clase_id => 223,  :cla_clase_id => 221, :clase_nombre => "Cubre Coches"},
	{:clase_id => 224,  :cla_clase_id => 221, :clase_nombre => "Monitores"},
	{:clase_id => 225,  :cla_clase_id => 221, :clase_nombre => "Rejas y Puertas"},
	{:clase_id => 226,  :cla_clase_id => 221, :clase_nombre => "Otros"},
	{:clase_id => 227,  :cla_clase_id => 171, :clase_nombre => "Sillas de Bebé para Autos"},
	{:clase_id => 228,  :cla_clase_id => 227, :clase_nombre => "Bebesit"},
	{:clase_id => 229,  :cla_clase_id => 227, :clase_nombre => "Century"},
	{:clase_id => 230,  :cla_clase_id => 227, :clase_nombre => "Evenflo"},
	{:clase_id => 231,  :cla_clase_id => 227, :clase_nombre => "Graco"},
	{:clase_id => 232,  :cla_clase_id => 227, :clase_nombre => "Infanti"},
	{:clase_id => 233,  :cla_clase_id => 227, :clase_nombre => "Otras Marcas"},
	{:clase_id => 234,  :cla_clase_id => 171, :clase_nombre => "Sillas de Bebé para Comer"},
	{:clase_id => 235,  :cla_clase_id => 171, :clase_nombre => "Sourvenirs"},
	{:clase_id => 236,  :cla_clase_id => 171, :clase_nombre => "Vestuario para Bebés"},
	{:clase_id => 237,  :cla_clase_id => 236, :clase_nombre => "Bodys"},
	{:clase_id => 238,  :cla_clase_id => 236, :clase_nombre => "Chalecos"},
	{:clase_id => 239,  :cla_clase_id => 236, :clase_nombre => "Chaquetas y Parkas"},
	{:clase_id => 240,  :cla_clase_id => 236, :clase_nombre => "Conjuntos"},
	{:clase_id => 241,  :cla_clase_id => 236, :clase_nombre => "Enteritos"},
	{:clase_id => 242,  :cla_clase_id => 236, :clase_nombre => "Gorros"},
	{:clase_id => 243,  :cla_clase_id => 236, :clase_nombre => "Jardineras"},
	{:clase_id => 244,  :cla_clase_id => 236, :clase_nombre => "Pantalones"},
	{:clase_id => 245,  :cla_clase_id => 236, :clase_nombre => "Pijamas"},
	{:clase_id => 246,  :cla_clase_id => 236, :clase_nombre => "Poleras"},
	{:clase_id => 247,  :cla_clase_id => 236, :clase_nombre => "Polerones"},
	{:clase_id => 248,  :cla_clase_id => 236, :clase_nombre => "Vestidos"},
	{:clase_id => 249,  :cla_clase_id => 236, :clase_nombre => "Zapatos"},
	{:clase_id => 250,  :cla_clase_id => 236, :clase_nombre => "Otros"},
	{:clase_id => 251,  :cla_clase_id => NULL, :clase_nombre => "Cámaras y Accesorios"},
	{:clase_id => 252,  :cla_clase_id => 251, :clase_nombre => "Accesorios para Cámaras"},
	{:clase_id => 253,  :cla_clase_id => 252, :clase_nombre => "Cables"},
	{:clase_id => 254,  :cla_clase_id => 252, :clase_nombre => "Controles Remotos"},
	{:clase_id => 255,  :cla_clase_id => 252, :clase_nombre => "Estuches y Bolsos"},
	{:clase_id => 256,  :cla_clase_id => 252, :clase_nombre => "Filtros"},
	{:clase_id => 257,  :cla_clase_id => 252, :clase_nombre => "Flashes e Iluminación"},
	{:clase_id => 258,  :cla_clase_id => 252, :clase_nombre => "Grips"},
	{:clase_id => 259,  :cla_clase_id => 252, :clase_nombre => "Lectores de Memoria"},
	{:clase_id => 260,  :cla_clase_id => 252, :clase_nombre => "Lentes"},
	{:clase_id => 261,  :cla_clase_id => 252, :clase_nombre => "Parasoles"},
	{:clase_id => 262,  :cla_clase_id => 252, :clase_nombre => "Tapas"},
	{:clase_id => 263,  :cla_clase_id => 252, :clase_nombre => "Trípodes"},
	{:clase_id => 264,  :cla_clase_id => 252, :clase_nombre => "Otros"},
	{:clase_id => 265,  :cla_clase_id => 251, :clase_nombre => "Cargadores, Baterías y Pilas"},
	{:clase_id => 266,  :cla_clase_id => 265, :clase_nombre => "Baterías"},
	{:clase_id => 267,  :cla_clase_id => 265, :clase_nombre => "Cargadores"},
	{:clase_id => 268,  :cla_clase_id => 265, :clase_nombre => "Pilas"},
	{:clase_id => 269,  :cla_clase_id => 265, :clase_nombre => "Otros"},
	{:clase_id => 270,  :cla_clase_id => 251, :clase_nombre => "Cámaras Antiguas y Colección"},
	{:clase_id => 271,  :cla_clase_id => 270, :clase_nombre => "Convencionales"},
	{:clase_id => 272,  :cla_clase_id => 270, :clase_nombre => "Instantaneas"},
	{:clase_id => 273,  :cla_clase_id => 270, :clase_nombre => "Otras"},
	{:clase_id => 274,  :cla_clase_id => 251, :clase_nombre => "Cámaras Automáticas"},
	{:clase_id => 275,  :cla_clase_id => 274, :clase_nombre => "Con Zoom"},
	{:clase_id => 276,  :cla_clase_id => 274, :clase_nombre => "Convencionales"},
	{:clase_id => 277,  :cla_clase_id => 274, :clase_nombre => "Otras"},
	{:clase_id => 278,  :cla_clase_id => 251, :clase_nombre => "Cámaras Digitales"},
	{:clase_id => 279,  :cla_clase_id => 278, :clase_nombre => "10 Megapixeles"},
	{:clase_id => 280,  :cla_clase_id => 278, :clase_nombre => "11 Megapixeles o Más"},
	{:clase_id => 281,  :cla_clase_id => 278, :clase_nombre => "3 Megapixeles"},
	{:clase_id => 282,  :cla_clase_id => 278, :clase_nombre => "4 Megapixeles"},
	{:clase_id => 286,  :cla_clase_id => 278, :clase_nombre => "5 Megapixeles"},
	{:clase_id => 288,  :cla_clase_id => 278, :clase_nombre => "6 Megapixeles"},
	{:clase_id => 289,  :cla_clase_id => 278, :clase_nombre => "7 Megapixeles"},
	{:clase_id => 290,  :cla_clase_id => 278, :clase_nombre => "8 Megapixeles"},
	{:clase_id => 291,  :cla_clase_id => 278, :clase_nombre => "9 Megapixeles"},
	{:clase_id => 292,  :cla_clase_id => 278, :clase_nombre => "Menos de 2.9 Megapixeles"},
	{:clase_id => 293,  :cla_clase_id => 251, :clase_nombre => "Cámaras Reflex"},
	{:clase_id => 294,  :cla_clase_id => 293, :clase_nombre => "Canon"},
	{:clase_id => 295,  :cla_clase_id => 293, :clase_nombre => "Minolta"},
	{:clase_id => 296,  :cla_clase_id => 293, :clase_nombre => "Nikon"},
	{:clase_id => 297,  :cla_clase_id => 293, :clase_nombre => "Pentax"},
	{:clase_id => 298,  :cla_clase_id => 293, :clase_nombre => "Zenit"},
	{:clase_id => 299,  :cla_clase_id => 293, :clase_nombre => "Otros"},
	{:clase_id => 300,  :cla_clase_id => 251, :clase_nombre => "Instrumentos Ópticos"},
	{:clase_id => 301,  :cla_clase_id => 300, :clase_nombre => "Binoculares"},
	{:clase_id => 302,  :cla_clase_id => 300, :clase_nombre => "Lupas"},
	{:clase_id => 303,  :cla_clase_id => 300, :clase_nombre => "Microscopios"},
	{:clase_id => 304,  :cla_clase_id => 300, :clase_nombre => "Telescopios"},
	{:clase_id => 305,  :cla_clase_id => 300, :clase_nombre => "Otros"},
	{:clase_id => 306,  :cla_clase_id => 251, :clase_nombre => "Marcos de Fotos Digitales"},
	{:clase_id => 307,  :cla_clase_id => 251, :clase_nombre => "Memorias Digitales"},
	{:clase_id => 308,  :cla_clase_id => 307, :clase_nombre => "Compact Flash"},
	{:clase_id => 309,  :cla_clase_id => 307, :clase_nombre => "Memory Stick / Pro"},
	{:clase_id => 310,  :cla_clase_id => 307, :clase_nombre => "Memory Stick Duo / Pro Duo"},
	{:clase_id => 311,  :cla_clase_id => 307, :clase_nombre => "SD - Secure Digital"},
	{:clase_id => 312,  :cla_clase_id => 307, :clase_nombre => "SDHC"},
	{:clase_id => 313,  :cla_clase_id => 307, :clase_nombre => "Otras"},
	{:clase_id => 314,  :cla_clase_id => 251, :clase_nombre => "Otros"},
	{:clase_id => 315,  :cla_clase_id => 251, :clase_nombre => "Papel Fotográfico"},
	{:clase_id => 316,  :cla_clase_id => 251, :clase_nombre => "Video Cámaras"},
	{:clase_id => 317,  :cla_clase_id => 316, :clase_nombre => "Con Disco Duro"},
	{:clase_id => 318,  :cla_clase_id => 316, :clase_nombre => "DVD"},
	{:clase_id => 319,  :cla_clase_id => 316, :clase_nombre => "Hi8, Digital8 y 8mm"},
	{:clase_id => 320,  :cla_clase_id => 316, :clase_nombre => "High Definition"},
	{:clase_id => 321,  :cla_clase_id => 316, :clase_nombre => "Mini DV"},
	{:clase_id => 322,  :cla_clase_id => 316, :clase_nombre => "VHS-C"},
	{:clase_id => 323,  :cla_clase_id => 316, :clase_nombre => "Otros Formatos"},
	{:clase_id => 324,  :cla_clase_id => NULL, :clase_nombre => "Celulares y Telefonía"},
	{:clase_id => 325,  :cla_clase_id => 324, :clase_nombre => "Accesorios para Celulares"},
	{:clase_id => 326,  :cla_clase_id => 325, :clase_nombre => "Adaptadores de Audio"},
	{:clase_id => 327,  :cla_clase_id => 325, :clase_nombre => "Adaptadores USB Bluetooth"},
	{:clase_id => 328,  :cla_clase_id => 325, :clase_nombre => "Antenas"},
	{:clase_id => 329,  :cla_clase_id => 325, :clase_nombre => "Baterías"},
	{:clase_id => 330,  :cla_clase_id => 325, :clase_nombre => "Cables de Audio y Video"},
	{:clase_id => 331,  :cla_clase_id => 325, :clase_nombre => "Cables de Datos"},
	{:clase_id => 332,  :cla_clase_id => 325, :clase_nombre => "Carcasas"},
	{:clase_id => 333,  :cla_clase_id => 325, :clase_nombre => "Cargadores"},
	{:clase_id => 334,  :cla_clase_id => 325, :clase_nombre => "Chips"},
	{:clase_id => 335,  :cla_clase_id => 325, :clase_nombre => "Flex"},
	{:clase_id => 336,  :cla_clase_id => 325, :clase_nombre => "Fundas y Estuches"},
	{:clase_id => 337,  :cla_clase_id => 325, :clase_nombre => "Láminas Protectoras"},
	{:clase_id => 338,  :cla_clase_id => 325, :clase_nombre => "Lápices y Uñetas"},
	{:clase_id => 339,  :cla_clase_id => 325, :clase_nombre => "Manos Libres"},
	{:clase_id => 340,  :cla_clase_id => 325, :clase_nombre => "Memorias"},
	{:clase_id => 341,  :cla_clase_id => 325, :clase_nombre => "Pantallas LCD"},
	{:clase_id => 342,  :cla_clase_id => 325, :clase_nombre => "Parlantes"},
	{:clase_id => 343,  :cla_clase_id => 325, :clase_nombre => "Soportes para Autos"},
	{:clase_id => 344,  :cla_clase_id => 325, :clase_nombre => "Teclados"},
	{:clase_id => 345,  :cla_clase_id => 325, :clase_nombre => "Tonos y Software"},
	{:clase_id => 346,  :cla_clase_id => 325, :clase_nombre => "Trackballs"},
	{:clase_id => 347,  :cla_clase_id => 325, :clase_nombre => "Otros"},
	{:clase_id => 348,  :cla_clase_id => 324, :clase_nombre => "Celulares"},
	{:clase_id => 349,  :cla_clase_id => 348, :clase_nombre => "Alcatel"},
	{:clase_id => 350,  :cla_clase_id => 348, :clase_nombre => "BlackBerry"},
	{:clase_id => 351,  :cla_clase_id => 348, :clase_nombre => "Cect"},
	{:clase_id => 352,  :cla_clase_id => 348, :clase_nombre => "HP - iPAQ"},
	{:clase_id => 353,  :cla_clase_id => 348, :clase_nombre => "HTC"},
	{:clase_id => 354,  :cla_clase_id => 348, :clase_nombre => "iPhone"},
	{:clase_id => 355,  :cla_clase_id => 348, :clase_nombre => "LG"},
	{:clase_id => 356,  :cla_clase_id => 348, :clase_nombre => "Motorola"},
	{:clase_id => 357,  :cla_clase_id => 348, :clase_nombre => "Nokia"},
	{:clase_id => 358,  :cla_clase_id => 348, :clase_nombre => "Palm Treo"},
	{:clase_id => 359,  :cla_clase_id => 348, :clase_nombre => "Samsung"},
	{:clase_id => 360,  :cla_clase_id => 348, :clase_nombre => "Siemens"},
	{:clase_id => 361,  :cla_clase_id => 348, :clase_nombre => "Sony Ericsson"},
	{:clase_id => 362,  :cla_clase_id => 348, :clase_nombre => "Otras Marcas"},
	{:clase_id => 363,  :cla_clase_id => 324, :clase_nombre => "Otros"},
	{:clase_id => 364,  :cla_clase_id => 324, :clase_nombre => "Radioaficionados"},
	{:clase_id => 365,  :cla_clase_id => 364, :clase_nombre => "Accesorios"},
	{:clase_id => 366,  :cla_clase_id => 364, :clase_nombre => "Equipos de Base"},
	{:clase_id => 367,  :cla_clase_id => 364, :clase_nombre => "Equipos Móviles"},
	{:clase_id => 368,  :cla_clase_id => 364, :clase_nombre => "Walkie Talkies"},
	{:clase_id => 369,  :cla_clase_id => 364, :clase_nombre => "Otros"},
	{:clase_id => 370,  :cla_clase_id => 324, :clase_nombre => "Teléfonos"},
	{:clase_id => 371,  :cla_clase_id => 370, :clase_nombre => "Centrales Telefónicas"},
	{:clase_id => 372,  :cla_clase_id => 370, :clase_nombre => "Faxes"},
	{:clase_id => 373,  :cla_clase_id => 370, :clase_nombre => "Telefonía IP"},
	{:clase_id => 374,  :cla_clase_id => 370, :clase_nombre => "Teléfonos Fijos"},
	{:clase_id => 375,  :cla_clase_id => 370, :clase_nombre => "Teléfonos Inalámbricos"},
	{:clase_id => 376,  :cla_clase_id => 370, :clase_nombre => "Teléfonos Públicos"},
	{:clase_id => 377,  :cla_clase_id => 370, :clase_nombre => "Otros"},
	{:clase_id => 378,  :cla_clase_id => NULL, :clase_nombre => "Computación"},
	{:clase_id => 379,  :cla_clase_id => 378, :clase_nombre => "Accesorios para Notebooks"},
	{:clase_id => 380,  :cla_clase_id => 379, :clase_nombre => "Adaptadores y Cargadores"},
	{:clase_id => 381,  :cla_clase_id => 379, :clase_nombre => "Baterías"},
	{:clase_id => 382,  :cla_clase_id => 379, :clase_nombre => "Bisagras"},
	{:clase_id => 383,  :cla_clase_id => 379, :clase_nombre => "Cables"},
	{:clase_id => 384,  :cla_clase_id => 379, :clase_nombre => "Candados de Seguridad"},
	{:clase_id => 385,  :cla_clase_id => 379, :clase_nombre => "Carcasas"},
	{:clase_id => 386,  :cla_clase_id => 379, :clase_nombre => "Controles Remotos"},
	{:clase_id => 387,  :cla_clase_id => 379, :clase_nombre => "Discos Duros"},
	{:clase_id => 388,  :cla_clase_id => 379, :clase_nombre => "Disketteras"},
	{:clase_id => 389,  :cla_clase_id => 379, :clase_nombre => "Docking Stations"},
	{:clase_id => 390,  :cla_clase_id => 379, :clase_nombre => "Flex"},
	{:clase_id => 391,  :cla_clase_id => 379, :clase_nombre => "Grabadores de CD y DVD"},
	{:clase_id => 392,  :cla_clase_id => 379, :clase_nombre => "Inversores"},
	{:clase_id => 393,  :cla_clase_id => 379, :clase_nombre => "Maletines, Bolsos y Fundas"},
	{:clase_id => 394,  :cla_clase_id => 379, :clase_nombre => "Memorias"},
	{:clase_id => 395,  :cla_clase_id => 379, :clase_nombre => "Pantallas"},
	{:clase_id => 396,  :cla_clase_id => 379, :clase_nombre => "Placas Madre"},
	{:clase_id => 397,  :cla_clase_id => 379, :clase_nombre => "Procesadores"},
	{:clase_id => 398,  :cla_clase_id => 379, :clase_nombre => "Tarjetas PCMCIA"},
	{:clase_id => 399,  :cla_clase_id => 379, :clase_nombre => "Teclados"},
	{:clase_id => 400,  :cla_clase_id => 379, :clase_nombre => "Ventiladores y Coolers"},
	{:clase_id => 401,  :cla_clase_id => 379, :clase_nombre => "Otros"},
	{:clase_id => 402,  :cla_clase_id => 378, :clase_nombre => "Cartuchos y Toners"},
	{:clase_id => 403,  :cla_clase_id => 402, :clase_nombre => "Cartuchos de Tinta"},
	{:clase_id => 404,  :cla_clase_id => 402, :clase_nombre => "Sistemas Continuos de Tinta"},
	{:clase_id => 405,  :cla_clase_id => 402, :clase_nombre => "Tintas y Recargas"},
	{:clase_id => 406,  :cla_clase_id => 402, :clase_nombre => "Toners"},
	{:clase_id => 407,  :cla_clase_id => 402, :clase_nombre => "Otros"},
	{:clase_id => 408,  :cla_clase_id => 378, :clase_nombre => "Componentes para PC"},
	{:clase_id => 409,  :cla_clase_id => 408, :clase_nombre => "Cables"},
	{:clase_id => 410,  :cla_clase_id => 408, :clase_nombre => "Coolers y Ventiladores"},
	{:clase_id => 411,  :cla_clase_id => 408, :clase_nombre => "Gabinetes"},
	{:clase_id => 412,  :cla_clase_id => 408, :clase_nombre => "Grabadores de DVD y CD"},
	{:clase_id => 413,  :cla_clase_id => 408, :clase_nombre => "Lectores de DVD y CD"},
	{:clase_id => 414,  :cla_clase_id => 408, :clase_nombre => "Tarjetas Controladoras"},
	{:clase_id => 415,  :cla_clase_id => 408, :clase_nombre => "Tarjetas de Sonido"},
	{:clase_id => 416,  :cla_clase_id => 408, :clase_nombre => "Otros"},
	{:clase_id => 417,  :cla_clase_id => 378, :clase_nombre => "Computadores"},
	{:clase_id => 418,  :cla_clase_id => 417, :clase_nombre => "AMD"},
	{:clase_id => 419,  :cla_clase_id => 417, :clase_nombre => "Apple"},
	{:clase_id => 420,  :cla_clase_id => 417, :clase_nombre => "Intel"},
	{:clase_id => 421,  :cla_clase_id => 417, :clase_nombre => "Otros"},
	{:clase_id => 422,  :cla_clase_id => 378, :clase_nombre => "DVDs y CDs Vírgenes"},
	{:clase_id => 423,  :cla_clase_id => 422, :clase_nombre => "CDs"},
	{:clase_id => 424,  :cla_clase_id => 422, :clase_nombre => "DVDs"},
	{:clase_id => 425,  :cla_clase_id => 422, :clase_nombre => "Otros"},
	{:clase_id => 426,  :cla_clase_id => 378, :clase_nombre => "Discos Duros"},
	{:clase_id => 427,  :cla_clase_id => 426, :clase_nombre => "Cases para Discos"},
	{:clase_id => 428,  :cla_clase_id => 426, :clase_nombre => "Discos Duros"},
	{:clase_id => 429,  :cla_clase_id => 426, :clase_nombre => "Otros"},
	{:clase_id => 430,  :cla_clase_id => 378, :clase_nombre => "Impresoras"},
	{:clase_id => 431,  :cla_clase_id => 430, :clase_nombre => "Inyección de Tinta"},
	{:clase_id => 432,  :cla_clase_id => 430, :clase_nombre => "Láser"},
	{:clase_id => 433,  :cla_clase_id => 430, :clase_nombre => "Matriz de Punto"},
	{:clase_id => 434,  :cla_clase_id => 430, :clase_nombre => "Multifuncional"},
	{:clase_id => 435,  :cla_clase_id => 430, :clase_nombre => "Plotters"},
	{:clase_id => 436,  :cla_clase_id => 430, :clase_nombre => "Repuestos y Accesorios"},
	{:clase_id => 437,  :cla_clase_id => 430, :clase_nombre => "Térmicas"},
	{:clase_id => 438,  :cla_clase_id => 430, :clase_nombre => "Otros"},
	{:clase_id => 439,  :cla_clase_id => 378, :clase_nombre => "Memorias RAM"},
	{:clase_id => 440,  :cla_clase_id => 439, :clase_nombre => "Para Notebooks"},
	{:clase_id => 441,  :cla_clase_id => 439, :clase_nombre => "Para PC"},
	{:clase_id => 442,  :cla_clase_id => 378, :clase_nombre => "Monitores y Proyectores"},
	{:clase_id => 443,  :cla_clase_id => 442, :clase_nombre => "Monitores"},
	{:clase_id => 444,  :cla_clase_id => 442, :clase_nombre => "Proyectores y Telones"},
	{:clase_id => 445,  :cla_clase_id => 442, :clase_nombre => "Otros"},
	{:clase_id => 446,  :cla_clase_id => 378, :clase_nombre => "Notebooks"},
	{:clase_id => 447,  :cla_clase_id => 446, :clase_nombre => "Acer"},
	{:clase_id => 448,  :cla_clase_id => 446, :clase_nombre => "Apple - iBook"},
	{:clase_id => 449,  :cla_clase_id => 446, :clase_nombre => "Apple - MacBook"},
	{:clase_id => 450,  :cla_clase_id => 446, :clase_nombre => "Apple - PowerBook"},		
	{:clase_id => 451,  :cla_clase_id => 446, :clase_nombre => "Asus"},
	{:clase_id => 452,  :cla_clase_id => 446, :clase_nombre => "Compaq"},
	{:clase_id => 453,  :cla_clase_id => 446, :clase_nombre => "Dell"},
	{:clase_id => 454,  :cla_clase_id => 446, :clase_nombre => "HP"},
	{:clase_id => 455,  :cla_clase_id => 446, :clase_nombre => "IBM y Lenovo"},
	{:clase_id => 456,  :cla_clase_id => 446, :clase_nombre => "Olidata"},
	{:clase_id => 457,  :cla_clase_id => 446, :clase_nombre => "Packard Bell"},
	{:clase_id => 458,  :cla_clase_id => 446, :clase_nombre => "Sony Vaio"},
	{:clase_id => 459,  :cla_clase_id => 446, :clase_nombre => "Toshiba"},
	{:clase_id => 460,  :cla_clase_id => 446, :clase_nombre => "Otras Marcas"},
	{:clase_id => 461,  :cla_clase_id => 378, :clase_nombre => "Otros"},
	{:clase_id => 462,  :cla_clase_id => 378, :clase_nombre => "Palms y PDA's"},
	{:clase_id => 463,  :cla_clase_id => 462, :clase_nombre => "Accesorios"},
	{:clase_id => 464,  :cla_clase_id => 462, :clase_nombre => "Blackberry"},
	{:clase_id => 465,  :cla_clase_id => 462, :clase_nombre => "HP y Compaq"},
	{:clase_id => 466,  :cla_clase_id => 462, :clase_nombre => "Palm y palmOne"},
	{:clase_id => 467,  :cla_clase_id => 462, :clase_nombre => "Otras Marcas"},
	{:clase_id => 468,  :cla_clase_id => 378, :clase_nombre => "Pen Drives"},
	{:clase_id => 469,  :cla_clase_id => 468, :clase_nombre => "2 GB"},
	{:clase_id => 470,  :cla_clase_id => 468, :clase_nombre => "4 GB"},
	{:clase_id => 471,  :cla_clase_id => 468, :clase_nombre => "8 GB o más"},
	{:clase_id => 472,  :cla_clase_id => 468, :clase_nombre => "Hasta 1 GB"},
	{:clase_id => 473,  :cla_clase_id => 378, :clase_nombre => "Periféricos y Accesorios de PC"},
	{:clase_id => 474,  :cla_clase_id => 474, :clase_nombre => "Adaptadores Bluetooth"},
	{:clase_id => 475,  :cla_clase_id => 474, :clase_nombre => "Audífonos"},
	{:clase_id => 476,  :cla_clase_id => 474, :clase_nombre => "Cables"},
	{:clase_id => 477,  :cla_clase_id => 474, :clase_nombre => "Hubs USB"},
	{:clase_id => 478,  :cla_clase_id => 474, :clase_nombre => "Joysticks"},
	{:clase_id => 479,  :cla_clase_id => 474, :clase_nombre => "Kits de Mouse y Teclado"},
	{:clase_id => 480,  :cla_clase_id => 474, :clase_nombre => "Mouse Pads"},
	{:clase_id => 481,  :cla_clase_id => 474, :clase_nombre => "Mouses"},
	{:clase_id => 482,  :cla_clase_id => 474, :clase_nombre => "Parlantes para PC"},
	{:clase_id => 483,  :cla_clase_id => 474, :clase_nombre => "Scanners"},
	{:clase_id => 484,  :cla_clase_id => 474, :clase_nombre => "Teclados"},
	{:clase_id => 485,  :cla_clase_id => 474, :clase_nombre => "Teléfonos VoIP"},
	{:clase_id => 486,  :cla_clase_id => 474, :clase_nombre => "Webcams"},
	{:clase_id => 487,  :cla_clase_id => 474, :clase_nombre => "Otros"},
	{:clase_id => 488,  :cla_clase_id => 378, :clase_nombre => "Placas Madre"},
	{:clase_id => 489,  :cla_clase_id => 488, :clase_nombre => "Procesadores AMD"},
	{:clase_id => 490,  :cla_clase_id => 488, :clase_nombre => "Procesadores Intel"},
	{:clase_id => 491,  :cla_clase_id => 488, :clase_nombre => "Otros"},
	{:clase_id => 492,  :cla_clase_id => 378, :clase_nombre => "Procesadores"},
	{:clase_id => 493,  :cla_clase_id => 492, :clase_nombre => "AMD Athlon"},
	{:clase_id => 494,  :cla_clase_id => 492, :clase_nombre => "AMD Sempron"},
	{:clase_id => 495,  :cla_clase_id => 492, :clase_nombre => "Intel Celeron"},
	{:clase_id => 496,  :cla_clase_id => 492, :clase_nombre => "Intel Core 2 Duo"},
	{:clase_id => 497,  :cla_clase_id => 492, :clase_nombre => "Intel Pentium 4 y Pentium D"},
	{:clase_id => 498,  :cla_clase_id => 492, :clase_nombre => "Intel Pentium III"},
	{:clase_id => 499,  :cla_clase_id => 492, :clase_nombre => "Otros"},
	{:clase_id => 500,  :cla_clase_id => 378, :clase_nombre => "Redes y Redes Inalámbricas"},
	{:clase_id => 501,  :cla_clase_id => 500, :clase_nombre => "Adaptadores USB WiFi"},
	{:clase_id => 502,  :cla_clase_id => 500, :clase_nombre => "Antenas"},
	{:clase_id => 503,  :cla_clase_id => 500, :clase_nombre => "Cables"},
	{:clase_id => 504,  :cla_clase_id => 500, :clase_nombre => "Modems"},
	{:clase_id => 505,  :cla_clase_id => 500, :clase_nombre => "Routers Convencionales"},
	{:clase_id => 506,  :cla_clase_id => 500, :clase_nombre => "Routers Inalámbricos"},
	{:clase_id => 507,  :cla_clase_id => 500, :clase_nombre => "Switches y Hubs"},
	{:clase_id => 508,  :cla_clase_id => 500, :clase_nombre => "Tarjetas de Red"},
	{:clase_id => 509,  :cla_clase_id => 500, :clase_nombre => "Tarjetas de Red Inalámbricas"},
	{:clase_id => 510,  :cla_clase_id => 500, :clase_nombre => "Otros"},
	{:clase_id => 511,  :cla_clase_id => 378, :clase_nombre => "Software"},
	{:clase_id => 512,  :cla_clase_id => 511, :clase_nombre => "Aplicaciones Comerciales"},
	{:clase_id => 513,  :cla_clase_id => 511, :clase_nombre => "Diseño"},
	{:clase_id => 514,  :cla_clase_id => 511, :clase_nombre => "Educativo"},
	{:clase_id => 515,  :cla_clase_id => 511, :clase_nombre => "Juegos"},
	{:clase_id => 516,  :cla_clase_id => 511, :clase_nombre => "Sistemas Operativos"},
	{:clase_id => 517,  :cla_clase_id => 511, :clase_nombre => "Otros"},
	{:clase_id => 518,  :cla_clase_id => 378, :clase_nombre => "Tarjetas de Video"},
	{:clase_id => 519,  :cla_clase_id => 518, :clase_nombre => "Capturadoras de Video"},
	{:clase_id => 520,  :cla_clase_id => 518, :clase_nombre => "Tarjetas de TV"},
	{:clase_id => 521,  :cla_clase_id => 518, :clase_nombre => "Tarjetas de Video"},
	{:clase_id => 522,  :cla_clase_id => 518, :clase_nombre => "Otros"},
	{:clase_id => 523,  :cla_clase_id => 378, :clase_nombre => "UPS y Fuentes"},
	{:clase_id => 524,  :cla_clase_id => 523, :clase_nombre => "Fuentes de Poder"},
	{:clase_id => 525,  :cla_clase_id => 523, :clase_nombre => "UPS"},
	{:clase_id => 526,  :cla_clase_id => 523, :clase_nombre => "Otros"},
	{:clase_id => 527,  :cla_clase_id => 378, :clase_nombre => "iPad y Tablets"},
	{:clase_id => 528,  :cla_clase_id => 527, :clase_nombre => "Accesorios"},
	{:clase_id => 529,  :cla_clase_id => 527, :clase_nombre => "Archos Tablet"},
	{:clase_id => 530,  :cla_clase_id => 527, :clase_nombre => "Blackberry Playbook Tablet"},
	{:clase_id => 531,  :cla_clase_id => 527, :clase_nombre => "iPad"},
	{:clase_id => 532,  :cla_clase_id => 527, :clase_nombre => "Kindle Amazon"},
	{:clase_id => 533,  :cla_clase_id => 527, :clase_nombre => "Motorola Xoom"},
	{:clase_id => 534,  :cla_clase_id => 527, :clase_nombre => "Samsung Galaxy Tab"},
	{:clase_id => 535,  :cla_clase_id => 527, :clase_nombre => "Sony Tablet"},
	{:clase_id => 536,  :cla_clase_id => 527, :clase_nombre => "ViewPad"},
	{:clase_id => 537,  :cla_clase_id => 527, :clase_nombre => "Otras Marcas"},
	{:clase_id => 538,  :cla_clase_id => NULL, :clase_nombre => "Consolas y Videojuegos"},
	{:clase_id => 539,  :cla_clase_id => 538, :clase_nombre => "Game Boy Advance"},
	{:clase_id => 540,  :cla_clase_id => 539, :clase_nombre => "Accesorios"},
	{:clase_id => 541,  :cla_clase_id => 539, :clase_nombre => "Consolas"},
	{:clase_id => 542,  :cla_clase_id => 539, :clase_nombre => "Juegos"},
	{:clase_id => 543,  :cla_clase_id => 539, :clase_nombre => "Otros"},
	{:clase_id => 544,  :cla_clase_id => 538, :clase_nombre => "GameCube"},
	{:clase_id => 545,  :cla_clase_id => 544, :clase_nombre => "Accesorios"},
	{:clase_id => 546,  :cla_clase_id => 544, :clase_nombre => "Consolas"},
	{:clase_id => 547,  :cla_clase_id => 544, :clase_nombre => "Juegos"},
	{:clase_id => 548,  :cla_clase_id => 544, :clase_nombre => "Otros"},
	{:clase_id => 549,  :cla_clase_id => 538, :clase_nombre => "Juegos para PC"},
	{:clase_id => 550,  :cla_clase_id => 549, :clase_nombre => "Juegos"},
	{:clase_id => 551,  :cla_clase_id => 549, :clase_nombre => "Otros"},
	{:clase_id => 552,  :cla_clase_id => 538, :clase_nombre => "Nintendo 3DS"},
	{:clase_id => 553,  :cla_clase_id => 552, :clase_nombre => "Consolas"},
	{:clase_id => 554,  :cla_clase_id => 552, :clase_nombre => "Juegos"},
	{:clase_id => 555,  :cla_clase_id => 552, :clase_nombre => "Otros"},
	{:clase_id => 556,  :cla_clase_id => 538, :clase_nombre => "Nintendo Ds"},
	{:clase_id => 557,  :cla_clase_id => 556, :clase_nombre => "Accesorios"},
	{:clase_id => 558,  :cla_clase_id => 556, :clase_nombre => "Consolas"},
	{:clase_id => 559,  :cla_clase_id => 556, :clase_nombre => "Juegos"},
	{:clase_id => 560,  :cla_clase_id => 556, :clase_nombre => "Otros"},
	{:clase_id => 561,  :cla_clase_id => 538, :clase_nombre => "Nintendo Wii"},
	{:clase_id => 562,  :cla_clase_id => 561, :clase_nombre => "Accesorios"},
	{:clase_id => 563,  :cla_clase_id => 561, :clase_nombre => "Consolas"},
	{:clase_id => 564,  :cla_clase_id => 561, :clase_nombre => "Juegos"},
	{:clase_id => 565,  :cla_clase_id => 561, :clase_nombre => "Otros"},
	{:clase_id => 566,  :cla_clase_id => 538, :clase_nombre => "Nintendo Wii U"},
	{:clase_id => 567,  :cla_clase_id => 566, :clase_nombre => "Accesorios"},
	{:clase_id => 568,  :cla_clase_id => 566, :clase_nombre => "Consolas"},
	{:clase_id => 569,  :cla_clase_id => 566, :clase_nombre => "Juegos"},
	{:clase_id => 570,  :cla_clase_id => 566, :clase_nombre => "Otros"},
	{:clase_id => 571,  :cla_clase_id => 538, :clase_nombre => "Otras Marcas"},
	{:clase_id => 572,  :cla_clase_id => 571, :clase_nombre => "Atari"},
	{:clase_id => 573,  :cla_clase_id => 571, :clase_nombre => "Gameboy"},
	{:clase_id => 574,  :cla_clase_id => 571, :clase_nombre => "Nintendo 64"},
	{:clase_id => 575,  :cla_clase_id => 571, :clase_nombre => "Nintendo Nes"},
	{:clase_id => 576,  :cla_clase_id => 571, :clase_nombre => "Sega Dreamcast"},
	{:clase_id => 577,  :cla_clase_id => 571, :clase_nombre => "Sega Genesis"},
	{:clase_id => 578,  :cla_clase_id => 571, :clase_nombre => "Otras"},
	{:clase_id => 579,  :cla_clase_id => 538, :clase_nombre => "PSP"},
	{:clase_id => 580,  :cla_clase_id => 579, :clase_nombre => "Accesorios"},
	{:clase_id => 581,  :cla_clase_id => 579, :clase_nombre => "Consolas"},
	{:clase_id => 582,  :cla_clase_id => 579, :clase_nombre => "Juegos"},
	{:clase_id => 583,  :cla_clase_id => 579, :clase_nombre => "Otros"},
	{:clase_id => 584,  :cla_clase_id => 538, :clase_nombre => "PlayStation 1 - PS1"},
	{:clase_id => 585,  :cla_clase_id => 584, :clase_nombre => "Accesorios"},
	{:clase_id => 586,  :cla_clase_id => 584, :clase_nombre => "Consolas"},
	{:clase_id => 587,  :cla_clase_id => 584, :clase_nombre => "Juegos"},
	{:clase_id => 588,  :cla_clase_id => 584, :clase_nombre => "Otros"},
	{:clase_id => 589,  :cla_clase_id => 538, :clase_nombre => "PlayStation 2 - PS2"},
	{:clase_id => 590,  :cla_clase_id => 589, :clase_nombre => "Accesorios"},
	{:clase_id => 591,  :cla_clase_id => 589, :clase_nombre => "Consolas"},
	{:clase_id => 592,  :cla_clase_id => 589, :clase_nombre => "Juegos"},
	{:clase_id => 593,  :cla_clase_id => 589, :clase_nombre => "Otros"},
	{:clase_id => 594,  :cla_clase_id => 538, :clase_nombre => "PlayStation 3 - PS3"},
	{:clase_id => 595,  :cla_clase_id => 594, :clase_nombre => "Accesorios"},
	{:clase_id => 596,  :cla_clase_id => 594, :clase_nombre => "Consolas"},
	{:clase_id => 597,  :cla_clase_id => 594, :clase_nombre => "Juegos"},
	{:clase_id => 598,  :cla_clase_id => 594, :clase_nombre => "PS Move"},
	{:clase_id => 599,  :cla_clase_id => 594, :clase_nombre => "Otros"},
	{:clase_id => 600,  :cla_clase_id => 538, :clase_nombre => "PlayStation Vita - PS Vita"},
	{:clase_id => 601,  :cla_clase_id => 600, :clase_nombre => "Playstation 4 - PS4"},
	{:clase_id => 602,  :cla_clase_id => 600, :clase_nombre => "Accesorios"},
	{:clase_id => 603,  :cla_clase_id => 600, :clase_nombre => "Consolas"},
	{:clase_id => 604,  :cla_clase_id => 600, :clase_nombre => "Juegos"},
	{:clase_id => 605,  :cla_clase_id => 600, :clase_nombre => "Otros"},
	{:clase_id => 606,  :cla_clase_id => 538, :clase_nombre => "Super Nintendo"},
	{:clase_id => 607,  :cla_clase_id => 606, :clase_nombre => "Accesorios"},
	{:clase_id => 608,  :cla_clase_id => 606, :clase_nombre => "Consolas"},
	{:clase_id => 609,  :cla_clase_id => 606, :clase_nombre => "Juegos"},
	{:clase_id => 610,  :cla_clase_id => 606, :clase_nombre => "Otros"},
	{:clase_id => 611,  :cla_clase_id => 538, :clase_nombre => "Xbox"},
	{:clase_id => 612,  :cla_clase_id => 611, :clase_nombre => "Consolas y Accesorios"},
	{:clase_id => 613,  :cla_clase_id => 611, :clase_nombre => "Juegos"},
	{:clase_id => 614,  :cla_clase_id => 611, :clase_nombre => "Otros"},
	{:clase_id => 615,  :cla_clase_id => 538, :clase_nombre => "Xbox 360"},
	{:clase_id => 616,  :cla_clase_id => 615, :clase_nombre => "Accesorios"},
	{:clase_id => 617,  :cla_clase_id => 615, :clase_nombre => "Consolas"},
	{:clase_id => 618,  :cla_clase_id => 615, :clase_nombre => "Juegos"},
	{:clase_id => 619,  :cla_clase_id => 615, :clase_nombre => "Kinect"},
	{:clase_id => 620,  :cla_clase_id => 615, :clase_nombre => "Otros"},
	{:clase_id => 621,  :cla_clase_id => 538, :clase_nombre => "Xbox One"},
	{:clase_id => 622,  :cla_clase_id => 621, :clase_nombre => "Consolas y Accesorios"},
	{:clase_id => 623,  :cla_clase_id => 621, :clase_nombre => "Juegos"},
	{:clase_id => 624,  :cla_clase_id => 621, :clase_nombre => "Otros"},	
]